### ISSUE TITLE
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL'

### ISSUE THREAD

**Issue by canadaduane** [alievk/avatarify#104]
I'm just following the Windows installation instructions and when running the `run_windows.bat` step I get the following error:

```
(avatarify) C:\Users\Johnsons\avatarify>run_windows.bat

(avatarify) C:\Users\Johnsons\avatarify>REM Web-camera device id

(avatarify) C:\Users\Johnsons\avatarify>set CAMID=0

(avatarify) C:\Users\Johnsons\avatarify>REM ################################################

(avatarify) C:\Users\Johnsons\avatarify>REM Normally you don't want to change settings below

(avatarify) C:\Users\Johnsons\avatarify>REM Conda environment name

(avatarify) C:\Users\Johnsons\avatarify>set CONDA_ENV_NAME=avatarify
Traceback (most recent call last):
  File "cam_fomm.py", line 18, in <module>
    from animate import normalize_kp
  File "C:\Users\Johnsons\avatarify\fomm\animate.py", line 7, in <module>
    from frames_dataset import PairedDataset
  File "C:\Users\Johnsons\avatarify\fomm\frames_dataset.py", line 10, in <module>
    from augmentation import AllAugmentationTransform
  File "C:\Users\Johnsons\avatarify\fomm\augmentation.py", line 13, in <module>
    import torchvision
  File "C:\Users\Johnsons\miniconda3\envs\avatarify\lib\site-packages\torchvision\__init__.py", line 2, in <module>
    from torchvision import datasets
  File "C:\Users\Johnsons\miniconda3\envs\avatarify\lib\site-packages\torchvision\datasets\__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "C:\Users\Johnsons\miniconda3\envs\avatarify\lib\site-packages\torchvision\datasets\fakedata.py", line 3, in <module>
    from .. import transforms
  File "C:\Users\Johnsons\miniconda3\envs\avatarify\lib\site-packages\torchvision\transforms\__init__.py", line 1, in <module>
    from .transforms import *
  File "C:\Users\Johnsons\miniconda3\envs\avatarify\lib\site-packages\torchvision\transforms\transforms.py", line 17, in <module>
    from . import functional as F
  File "C:\Users\Johnsons\miniconda3\envs\avatarify\lib\site-packages\torchvision\transforms\functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (C:\Users\Johnsons\miniconda3\envs\avatarify\lib\site-packages\PIL\__init__.py)
```

I downloaded miniconda3 version 3.7 for windows 64-bit.

**Comment by canadaduane** [comment]
I just noticed this in the `PIL\__init__.py`:

```
Use PIL.__version__ for this Pillow version.

;-)
"""

from . import _version

# VERSION was removed in Pillow 6.0.0.
# PILLOW_VERSION was removed in Pillow 7.0.0.
# Use __version__ instead.
__version__ = _version.__version__
```

**Comment by canadaduane** [comment]
Changing line 5 in `functional.py` seemed to do the trick:

```
from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
```

to

```
from PIL import Image, ImageOps, ImageEnhance, __version__ as PILLOW_VERSION
```

C:\Users\Johnsons\miniconda3\envs\avatarify\lib\site-packages\torchvision\transforms\functional.py

**Comment by PlymouthUniversitySolDev** [comment]
Changed line 5 to __version__ (without 'as PILLOW_VERSION') and that worked too!

**Comment by alievk** [comment]
What pillow version do you have?

```
conda activate avatarify
pip show pillow
```

**Comment by cavejay** [comment]
I have the same stack trace with a pillow version of 7.0.0

```
(avatarify) M:\Programs and Files\avatarify>set CONDA_ENV_NAME=avatarify
Traceback (most recent call last):
  File "cam_fomm.py", line 18, in <module>
    from animate import normalize_kp
  File "M:\Programs and Files\avatarify\fomm\animate.py", line 7, in <module>
    from frames_dataset import PairedDataset
  File "M:\Programs and Files\avatarify\fomm\frames_dataset.py", line 10, in <module>
    from augmentation import AllAugmentationTransform
  File "M:\Programs and Files\avatarify\fomm\augmentation.py", line 13, in <module>
    import torchvision
  File "C:\Users\cavejay\.conda\envs\avatarify\lib\site-packages\torchvision\__init__.py", line 2, in <module>
    from torchvision import datasets
  File "C:\Users\cavejay\.conda\envs\avatarify\lib\site-packages\torchvision\datasets\__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "C:\Users\cavejay\.conda\envs\avatarify\lib\site-packages\torchvision\datasets\fakedata.py", line 3, in <module>
    from .. import transforms
  File "C:\Users\cavejay\.conda\envs\avatarify\lib\site-packages\torchvision\transforms\__init__.py", line 1, in <module>
    from .transforms import *
  File "C:\Users\cavejay\.conda\envs\avatarify\lib\site-packages\torchvision\transforms\transforms.py", line 17, in <module>
    from . import functional as F
  File "C:\Users\cavejay\.conda\envs\avatarify\lib\site-packages\torchvision\transforms\functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (C:\Users\cavejay\.conda\envs\avatarify\lib\site-packages\PIL\__init__.py)

(avatarify) M:\Programs and Files\avatarify>pip show pillow
Name: Pillow
Version: 7.0.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Alex Clark (PIL Fork Author)
Author-email: aclark@python-pillow.org
License: HPND
Location: c:\users\cavejay\.conda\envs\avatarify\lib\site-packages
Requires:
Required-by: torchvision, scikit-image, imageio
```

**Comment by alievk** [comment]
That's the issue, pillow must be <7.0.0.

I'm preparing a big fix for package versions.

**Comment by alievk** [comment]
https://github.com/alievk/avatarify/issues/107

**Comment by jamezm79** [comment]
I get the same issue. How do I download a lower pillow version?

**Comment by alievk** [comment]
Please fetch the latest version and install avatarify from scratch.
