### ISSUE TITLE
please,what's wrong

### ISSUE THREAD

**Issue by jackylee1** [alievk/avatarify#126]
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\conda\envs\avatarify\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ANBANG~1\\AppData\\Local\\Temp\\pip-install-lcrjo7zr\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\ANBANG~1\\AppData\\Local\\Temp\\pip-install-lcrjo7zr\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ANBANG~1\AppData\Local\Temp\pip-wheel-jrpinroz'
       cwd: C:\Users\ANBANG~1\AppData\Local\Temp\pip-install-lcrjo7zr\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ANBANG~1\AppData\Local\Temp\pip-install-lcrjo7zr\torch\setup.py", line 265, in <module>
      description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
    File "D:\conda\envs\avatarify\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "D:\conda\envs\avatarify\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\conda\envs\avatarify\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\conda\envs\avatarify\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\conda\envs\avatarify\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "D:\conda\envs\avatarify\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\conda\envs\avatarify\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\conda\envs\avatarify\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\conda\envs\avatarify\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\conda\envs\avatarify\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\ANBANG~1\AppData\Local\Temp\pip-install-lcrjo7zr\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'D:\conda\envs\avatarify\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ANBANG~1\\AppData\\Local\\Temp\\pip-install-lcrjo7zr\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\ANBANG~1\\AppData\\Local\\Temp\\pip-install-lcrjo7zr\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\ANBANG~1\AppData\Local\Temp\pip-install-lcrjo7zr\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
Installing collected packages: cloudpickle, six, cycler, dask, decorator, numpy, Pillow, imageio, kiwisolver, pytz, pyparsing, python-dateutil, matplotlib, networkx, pandas, pycparser, pygit, PyWavelets, PyYAML, scikit-image, scikit-learn, scipy, toolz, tqdm, urllib3, idna, chardet, requests, opencv-python, torch, face-alignment, pyfakewebcam

**Comment by jackylee1** [comment]
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\conda\envs\avatarify\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ANBANG~1\\AppData\\Local\\Temp\\pip-install-lcrjo7zr\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\ANBANG~1\\AppData\\Local\\Temp\\pip-install-lcrjo7zr\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ANBANG~1\AppData\Local\Temp\pip-wheel-jrpinroz'
       cwd: C:\Users\ANBANG~1\AppData\Local\Temp\pip-install-lcrjo7zr\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ANBANG~1\AppData\Local\Temp\pip-install-lcrjo7zr\torch\setup.py", line 265, in <module>
      description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
    File "D:\conda\envs\avatarify\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "D:\conda\envs\avatarify\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\conda\envs\avatarify\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\conda\envs\avatarify\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\conda\envs\avatarify\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "D:\conda\envs\avatarify\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\conda\envs\avatarify\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\conda\envs\avatarify\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\conda\envs\avatarify\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\conda\envs\avatarify\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\ANBANG~1\AppData\Local\Temp\pip-install-lcrjo7zr\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'D:\conda\envs\avatarify\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ANBANG~1\\AppData\\Local\\Temp\\pip-install-lcrjo7zr\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\ANBANG~1\\AppData\\Local\\Temp\\pip-install-lcrjo7zr\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\ANBANG~1\AppData\Local\Temp\pip-install-lcrjo7zr\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
Installing collected packages: cloudpickle, six, cycler, dask, decorator, numpy, Pillow, imageio, kiwisolver, pytz, pyparsing, python-dateutil, matplotlib, networkx, pandas, pycparser, pygit, PyWavelets, PyYAML, scikit-image, scikit-learn, scipy, toolz, tqdm, urllib3, idna, chardet, requests, opencv-python, torch, face-alignment, pyfakewebcam

**Comment by jackylee1** [comment]
hi ,alievk. i don't know what's wrong,i just can not finish it.can you please help
