### ISSUE TITLE
Error "cam_fomm.py" import cv2

### ISSUE THREAD

**Issue by Paulex-Git** [alievk/avatarify#137]
When i run on Mac, i get this errors:

`Traceback (most recent call last):
  File "cam_fomm.py", line 11, in <module>
    import cv2
  File "/Users/---/opt/miniconda3/envs/avatarify/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: dlopen(/Users/---/opt/miniconda3/envs/avatarify/lib/python3.7/site-packages/cv2/cv2.cpython-37m-darwin.so, 2): Symbol not found: _inflateValidate
  Referenced from: /Users/---/opt/miniconda3/envs/avatarify/lib/python3.7/site-packages/cv2/.dylibs/libpng16.16.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libz.1.dylib
 in /Users/---/opt/miniconda3/envs/avatarify/lib/python3.7/site-packages/cv2/.dylibs/libpng16.16.dylib
`
Any help will be appreciated.

**Comment by karfly** [comment]
Hi, @Paulex-Git!
What version of Mac OSX do you have?

**Comment by harpreets** [comment]
@karfly I'm getting the same on OS Sierra 10.12.1. 
[[Can't update my OS at the moment for other programs.]] Any other resolution?

**Comment by Paulex-Git** [comment]
@karfly OS Sierra 10.12.2

**Comment by bobvo23** [comment]
I can confirm that this is a good enhancement:
Infact, just change the "requirements_client.txt" value, the bash script will automatically install the indicated version, 3.4.5.20

**Comment by bobvo23** [comment]
> Hi, @Paulex-Git!
> What version of Mac OSX do you have? If Catalina [this link](https://github.com/AlexEMG/DeepLabCut/issues/608) can help.

Upgrading to Catalina will resolve the issue. Though it could be a bit much to run the program. The numpy version change can resolve the issue.

**Comment by joedicks911** [comment]
How can I  resolve the same error for windows?

**Comment by SanPatrick01** [comment]
What error... video or pic 
But here is a video I made for you all on YouTube...

Avatarify windows installation
https://youtu.be/sylE-uIhNCw
