### ISSUE TITLE
Package avatarify

### ISSUE THREAD

**Issue by MartinDelille** [alievk/avatarify#152]
Most of the people posting issue struggle to install avatarify on their computer. Having a package working on all OS would reduce support effort and allow developers to focus on more important stuff:
-  bug fix
- stability improvement
- new features

I'm quite noob at python packaging but would be happy to learn/help!

**Comment by E3V3A** [comment]
>  Having a package working on all OS

The devil's in the details! The issue is not a package, but the wide variety of hardware and OS configurations people use. So while it is doable and a great thing to do, it's not currently maintainable, since nobody want to provide all the detailed and varied installation instructions required. Even following the README to point, you will soon find that you might be missing something assumed to be already there... 

New/old CUDA drivers, different card, UTF-16 username, different drive, already have multiple python versions in path? What are their default shell? CMD, Powershell, or pwsh? (That's only on Windows.)

Start making an installation script for your OS and setup, and post it here and @alievk can put it in the Wiki maybe?

**Comment by alievk** [comment]
I'm trying to distillate all incoming issues into short instructions. If the issue becomes common, it goes into the README. When it grows to large I move some parts to the Wiki. The point is to keep the documentation neat.

But there're still people posting issues like `vox-adv-cpk.pth.tar not found`, since some of them probably have opened the first terminal window in their life. And that's great to see!

To this end, there's no silver bullet for making documentation ideal, we have to support these enthusiasts through communication. Many of them are not even aware of the concept of the Wiki in GitHub. But anyway, thanks for keeping this topic open!

**Comment by Goodweek** [comment]
when i run_windows.bat:
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 218, in <module>
    **predictor_args
  File "C:\Users\viv\avatarify-python\afy\predictor_local.py", line 49, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "C:\Users\viv\anaconda3\envs\avatarify\lib\site-packages\face_alignment\api.py", line 75, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "C:\Users\viv\anaconda3\envs\avatarify\lib\site-packages\face_alignment\detection\sfd\sfd_detector.py", line 24, in __init__
    model_weights = load_url(models_urls['s3fd'])
  File "C:\Users\viv\anaconda3\envs\avatarify\lib\site-packages\torch\hub.py", line 559, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "C:\Users\viv\anaconda3\envs\avatarify\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\viv\anaconda3\envs\avatarify\lib\site-packages\torch\serialization.py", line 781, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 8817910 more bytes. The file might be corrupted.

vox-adv-cpk.pth.tar 
The compressed file format is unknown or the data has been corrupted
how to fix it ?
My computer is win11, GPU RTX3060

**Comment by JohanAR** [comment]
@Goodweek Don't comment on random existing github issues, your problem has nothing to do with this feature request.

The obvious thing to try would be to delete the corrupted file and try downloading it again. If that doesn't work, open a new issue.
