### ISSUE TITLE
Avatarify Conda Environment Error

### ISSUE THREAD

**Issue by ByFxbian** [alievk/avatarify#180]
I wanted to ask you guys if you could help me with Avatarify. Since it can't be opened I added "cmd /k", now I can see what error I get. I get the error -->

> Could not find conda environment: avatarify
> You can list all discoverable environments with 'conda info --envs'.

> Traceback (most recent call last):
>   File "afy/cam_fomm.py", line 3, in <module>
>      import yaml
> ModuleNotFoundError: No module named 'yaml'

Unfortunately I do not know how to fix this one. I have already reinstalled Miniconda. 
Kind regards 
Fabianq

**Comment by GiuseppeGiacoppo** [comment]
I have the same issue. I think there's some bug when configuring the conda env.
You can solve this issue by invoking:
`pip install pyyaml`

I had other missing modules, so I had to look for them online and install the proper pip package

**Comment by Gimel-ai** [comment]
Hi, 

I am having the same issues I have tried all the options here and nothing help, please give me some advise. 

` ~/Documents/GitHub/avatarify   master ● ?  ./run_mac.sh --is-client --in-addr tcp://0.tcp.ngrok.io:15561 --out-addr tcp://2.tcp.ngrok.io:10962
Could not find conda environment: avatarify
You can list all discoverable environments with `conda info --envs`.

Traceback (most recent call last):
  File "afy/cam_fomm.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
 ~/Documents/GitHub/avatarify   master ● ?  python3                         1 ↵  696  17:55:32
Python 3.7.3 (default, Jun  2 2020, 19:48:59)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> ^D
 ~/Documents/GitHub/avatarify   master ● ?  python                            ✔  697  17:55:44

WARNING: Python 2.7 is not recommended.
This version is included in macOS for compatibility with legacy software.
Future versions of macOS will not include Python 2.7.
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Apr 17 2020, 18:29:03)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> ^D
 ~/Documents/GitHub/avatarify   master ● ?  pip install pyyaml                ✔  698  17:55:51
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyyaml in /Library/Python/2.7/site-packages (5.3.1)
 ~/Documents/GitHub/avatarify   master ● ?  sudo pip3 install pyyaml          ✔  699  17:56:16
Password:
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/Users/rubenfernandez/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pyyaml in /Library/Python/2.7/site-packages (5.3.1)
 ~/Documents/GitHub/avatarify   master ● ?                                    ✔  700  17:56:31
`

As you can see there the yaml is satisfied and I have ran with different python and still same problem.

**Comment by ChrisCrossTheUniverse** [comment]
I saw in another post that it should be written like this, and it worked for me.
pip install PyYAML
For windows:
python -m pip install PyYAML

**Comment by JohanAR** [comment]
@Gimel-ai your first error says "Could not find conda environment: avatarify", this makes it sound like there was a failure when you ran the install_mac.sh script. After that pip and python should run inside the conda environment, I think you're running your system Python.

**Comment by theyrneh** [comment]
https://stackoverflow.com/questions/58369030/could-not-find-conda-environment

follow this one, it works for me

**Comment by ichyTao** [comment]
I have the same issue saying EnvironmentNameNotFound: Could not find conda environment: avatarify
You can list all discoverable environments with `conda info --envs`.


[1703241691.418587] Loading Predictor
[1703241691.918540] Receiving from tcp://0.tcp.eu.ngrok.io:10513

I have tried everything but still not working out. Can somebody help out

**Comment by SanPatrick01** [comment]
Is that colab??

**Comment by ichyTao** [comment]
> Is that colab??

Yes, It is.

**Comment by SanPatrick01** [comment]
‪+234 811 513 3627‬
Download anydesk and send to the WhatsApp
