### ISSUE TITLE
ValueError: Could not broadcast input array

### ISSUE THREAD

**Issue by GuiGusTrem** [alievk/avatarify#188]
Got ValueError: Could not broadcast input array from shape (240,320,3) into shape (0.320.3)
at step 6 of Windows installation (Run run_windows.bat. If installation was successful, two windows "cam" and "avatarify" will appear. Leave these windows open for the next installation steps.)
The windows do not appear.

**Comment by alievk** [comment]
Could you show the entire output?

**Comment by GuiGusTrem** [comment]
(base) C:\>cd avatarify

(base) C:\avatarify>run_windows.bat
[1590503183.713614] Loading Predictor
C:\avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[1590503188.927704] Trying camera with id 0
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
[1590503189.722848] Trying camera with id 1
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
[1590503890.114888] Trying camera with id 2
[1590503890.688625] Trying camera with id 3
[1590503890.690623] Camera with id 3 is not available
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 180, in <module>
    cam_id = select_camera(config)
  File "afy/cam_fomm.py", line 131, in select_camera
    cam_id = cam_selector.select_camera(cam_frames, window="CLICK ON YOUR CAMERA")
  File "C:\avatarify\afy\camera_selector.py", line 67, in select_camera
    grid = make_grid(cam_frames, cols=grid_cols)
  File "C:\avatarify\afy\camera_selector.py", line 50, in make_grid
    grid[r * h0:(r + 1) * h0, c * w0:(c + 1) * w0] = img[..., :3]
ValueError: could not broadcast input array from shape (240,320,3) into shape (0,320,3)

(avatarify) C:\avatarify>

**Comment by alievk** [comment]
Thank you for the report! I have found and fixed the bug, please pull the latest commit.
