### ISSUE TITLE
Not sure what the problem could be?

### ISSUE THREAD

**Issue by mrreapz** [alievk/avatarify#189]
One window with my frozen webcam appears and I get this error. Thanks!

(base) C:\Users\Andrew\avatarify>run_windows.bat
[1590515768.703851] Loading Predictor
C:\Users\Andrew\avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[1590515772.734650] Trying camera with id 0
[1590515774.302460] Trying camera with id 1
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderC[1590515774.305436] Camera with id 1 is not available
B[1590515774.305932] Trying camera with id 2
::~SourceReaderCB terminati[1590515774.306924] Camera with id 2 is not available
[1590515774.307420] Trying camera with id 3
ng async callback
[1590515774.308413] Camera with id 3 is not available
Traceback (most recent call last):
  File "C:\Users\Andrew\avatarify\afy\camera_selector.py", line 63, in mouse_callback
    if camid < len(cam_frames):
NameError: name 'cam_frames' is not defined
Traceback (most recent call last):
  File "C:\Users\Andrew\avatarify\afy\camera_selector.py", line 63, in mouse_callback
    if camid < len(cam_frames):
NameError: name 'cam_frames' is not defined

**Comment by alievk** [comment]
That was a bug creeped in the last commit, sorry :|
Please pull the latest commit.

**Comment by JohanAR** [comment]
Should be solved
