### ISSUE TITLE
Cannot find confine to.... settings in CamTwist v3.4.3

### ISSUE THREAD

**Issue by inglesuniversal** [alievk/avatarify#190]
Also, after running the command on my Mac... All I get is this text:

./run_mac.sh --is-client --in-addr tcp://0.tcp.ngrok.io:xxxxx --out-addr tcp://0.tcp.ngrok.io:xxxxx
Loading Predictor
Receiving from tcp://0.tcp.ngrok.io:xxxxx
Sending to tcp://0.tcp.ngrok.io:xxxxx
 SEND 1.167 (1.167)

and If I got into zoom I get to choose camera (CamTwist) but no avatar is shown on preview

Never had any errors while installing and using Google Remote connection

**Comment by alievk** [comment]
So the client just hangs, right?
Could you show the logs from the Colab?

**Comment by inglesuniversal** [comment]
UPDATE:

I tried the script again and... a tiny camera showed up with number 2 on the upper left corner. Am I supposed to have CamTwist running first? I can only select webcam which is FaceTime cam... I cannot find the additional setting screen you mention on the instructions.

ZOOM mac app has latest version... ran command line first (no errors)... it was not running at the time of test.


CODES from code lab:

[1590617377.245862] Loading Predictor

[1590618000.394967] recv timeout
[1590618001.395743] recv timeout
[1590618002.396938] recv timeout
[1590618003.398144] recv timeout
[1590618004.399369] recv timeout
[1590618005.400550] recv timeout
[1590618006.401768] recv timeout
[1590618007.402972] recv timeout
[1590618008.404191] recv timeout
[1590618009.405399] recv timeout
[1590618010.406591] recv timeout
[1590618011.407899] recv timeout
[1590618012.409170] recv timeout
[1590618013.410372] recv timeout
[1590618014.411627] recv timeout
[1590618015.412845] recv timeout
[1590618016.414072] recv timeout
[1590618017.415259] recv timeout
[1590618018.416613] recv timeout
[1590618019.417887] recv timeout
[1590618020.419109] recv timeout
[1590618021.420326] recv timeout
[1590618022.421575] recv timeout
[1590618023.422802] recv timeout
[1590618024.424023] recv timeout
[1590618025.425285] recv timeout
[1590618026.426589] recv timeout
[1590618027.427835] recv timeout
[1590618028.429107] recv timeout
[1590618029.430295] recv timeout
[1590618030.431521] recv timeout
[1590618031.432811] recv timeout
[1590618032.434003] recv timeout
[1590618033.435192] recv timeout
[1590618034.436430] recv timeout
[1590618035.437702] recv timeout
[1590618036.438938] recv timeout
[1590618037.440187] recv timeout
[1590618038.440463] recv timeout
[1590618039.441477] recv timeout
[1590618040.442684] recv timeout
[1590618041.443932] recv timeout
[1590618042.445162] recv timeout
[1590618043.445567] recv timeout
[1590618044.446773] recv timeout
[1590618045.447992] recv timeout
[1590618046.449204] recv timeout
[1590618047.450454] recv timeout
[1590618048.451701] recv timeout
[1590618049.453006] recv timeout
[1590618050.454318] recv timeout
[1590618051.455675] recv timeout
[1590618052.456877] recv timeout
[1590618053.457428] recv timeout
[1590618054.458630] recv timeout
[1590618055.459284] recv timeout
[1590618056.460497] recv timeout
[1590618057.461677] recv timeout
[1590618058.462872] recv timeout
[1590618059.464062] recv timeout
[1590618060.465259] recv timeout
[1590618061.466471] recv timeout
[1590618062.467740] recv timeout
[1590618063.468960] recv timeout
[1590618064.470222] recv timeout
[1590618065.471491] recv timeout
[1590618066.472694] recv timeout
[1590618067.474026] recv timeout
[1590618068.475363] recv timeout
[1590618069.476578] recv timeout
[1590618070.477776] recv timeout
[1590618071.479054] recv timeout
[1590618072.480254] recv timeout
[1590618073.481491] recv timeout
[1590618074.482769] recv timeout
[1590618075.484035] recv timeout
[1590618076.485241] recv timeout
[1590618077.486516] recv timeout
[1590618078.487728] recv timeout
[1590618079.488384] recv timeout
[1590618080.489589] recv timeout
[1590618081.490795] recv timeout
[1590618082.492005] recv timeout
[1590618083.493216] recv timeout
[1590618084.494438] recv timeout
[1590618085.495536] recv timeout
[1590618086.496741] recv timeout
[1590618087.497975] recv timeout
[1590618088.499189] recv timeout
[1590618089.500414] recv timeout
[1590618090.501608] recv timeout
[1590618091.502822] recv timeout
[1590618092.503449] recv timeout
[1590618093.504597] recv timeout
[1590618094.505890] recv timeout
[1590618095.506422] recv timeout
[1590618096.507686] recv timeout
[1590618097.508871] recv timeout
[1590618098.510053] recv timeout
[1590618099.510411] recv timeout

[1590617592.121361] working on {'name': '__init__', 'critical': True, 'id': 0}
[1590617604.861367] Initialized predictor with: [[], {'config_path': 'fomm/config/vox-adv-256.yaml', 'checkpoint_path': 'vox-adv-cpk.pth.tar', 'relative': True, 'adapt_movement_scale': True, 'enc_downscale': 1}]
[1590617604.861875] UNPACK 0.081 (0.081)		CALL 0.004 (0.004)		PACK 0.034 (0.034)		
[1590617698.046241] working on {'name': '__init__', 'critical': True, 'id': 0}
[1590617698.046391] Same config as before... reusing previous predictor
[1590617698.046488] UNPACK 0.030 (0.056)		CALL 0.001 (0.002)		PACK 0.041 (0.037)		
[1590617842.496721] working on {'name': '__init__', 'critical': True, 'id': 0}
[1590617842.496805] Same config as before... reusing previous predictor
[1590617842.496890] UNPACK 0.028 (0.046)		CALL 0.001 (0.002)		PACK 0.035 (0.037)		
[1590617904.283941] working on {'name': '__init__', 'critical': True, 'id': 0}
[1590617904.284021] Same config as before... reusing previous predictor
[1590617904.284108] UNPACK 0.024 (0.041)		CALL 0.001 (0.002)		PACK 0.039 (0.037)

[1590618006.401749] send queue empty
[1590618007.402956] send queue empty
[1590618008.404159] send queue empty
[1590618009.405381] send queue empty
[1590618010.406576] send queue empty
[1590618011.407865] send queue empty
[1590618012.409134] send queue empty
[1590618013.410473] send queue empty
[1590618014.411645] send queue empty
[1590618015.412833] send queue empty
[1590618016.414042] send queue empty
[1590618017.415247] send queue empty
[1590618018.416582] send queue empty
[1590618019.417857] send queue empty
[1590618020.419075] send queue empty
[1590618021.420304] send queue empty
[1590618022.421541] send queue empty
[1590618023.422765] send queue empty
[1590618024.423994] send queue empty
[1590618025.425263] send queue empty
[1590618026.426565] send queue empty
[1590618027.427815] send queue empty
[1590618028.429073] send queue empty
[1590618029.430272] send queue empty
[1590618030.431500] send queue empty
[1590618031.432777] send queue empty
[1590618032.433977] send queue empty
[1590618033.435186] send queue empty
[1590618034.436390] send queue empty
[1590618035.437672] send queue empty
[1590618036.438898] send queue empty
[1590618037.440351] send queue empty
[1590618038.441424] send queue empty
[1590618039.442415] send queue empty
[1590618040.443603] send queue empty
[1590618041.444794] send queue empty
[1590618042.445683] send queue empty
[1590618043.446863] send queue empty
[1590618044.448045] send queue empty
[1590618045.449243] send queue empty
[1590618046.449456] send queue empty
[1590618047.450448] send queue empty
[1590618048.451685] send queue empty
[1590618049.452991] send queue empty
[1590618050.454307] send queue empty
[1590618051.455664] send queue empty
[1590618052.456868] send queue empty
[1590618053.458062] send queue empty
[1590618054.459089] send queue empty
[1590618055.460288] send queue empty
[1590618056.461461] send queue empty
[1590618057.462603] send queue empty
[1590618058.463765] send queue empty
[1590618059.464919] send queue empty
[1590618060.466068] send queue empty
[1590618061.467219] send queue empty
[1590618062.468384] send queue empty
[1590618063.469573] send queue empty
[1590618064.470724] send queue empty
[1590618065.471873] send queue empty
[1590618066.473020] send queue empty
[1590618067.474211] send queue empty
[1590618068.475309] send queue empty
[1590618069.476544] send queue empty
[1590618070.477760] send queue empty
[1590618071.479022] send queue empty
[1590618072.480238] send queue empty
[1590618073.481475] send queue empty
[1590618074.482738] send queue empty
[1590618075.484003] send queue empty
[1590618076.485210] send queue empty
[1590618077.486484] send queue empty
[1590618078.487686] send queue empty
[1590618079.488358] send queue empty
[1590618080.489575] send queue empty
[1590618081.490783] send queue empty
[1590618082.491994] send queue empty
[1590618083.493203] send queue empty
[1590618084.494429] send queue empty
[1590618085.495540] send queue empty
[1590618086.496734] send queue empty
[1590618087.497965] send queue empty
[1590618088.499171] send queue empty
[1590618089.500394] send queue empty
[1590618090.501594] send queue empty
[1590618091.502811] send queue empty
[1590618092.503394] send queue empty
[1590618093.504578] send queue empty
[1590618094.505865] send queue empty
[1590618095.507060] send queue empty
[1590618096.508200] send queue empty
[1590618097.509369] send queue empty
[1590618098.510512] send queue empty
[1590618099.511657] send queue empty
[1590618100.511867] send queue empty
[1590618101.513049] send queue empty
[1590618102.514230] send queue empty
[1590618103.515378] send queue empty
[1590618104.516528] send queue empty
[1590618105.517670] send queue empty

LAST PLAY BUTTON BOX empty even after pressing button


Hope this info is helpful

**Comment by inglesuniversal** [comment]
LOCAL TERMINAL LOG:

$ ./run_mac.sh --is-client --in-addr tcp://0.tcp.ngrok.io:XXXXXX --out-addr tcp://0.tcp.ngrok.io:XXXXXX
[1590617903.484867] Loading Predictor
[1590617903.558303] Receiving from tcp://0.tcp.ngrok.io:XXXXX
[1590617903.558304] Sending to tcp://0.tcp.ngrok.io:XXXXX
[1590617903.561386] SEND 0.525 (0.525)		
[1590617904.319835] RECV 759.540 (759.540)		
[1590617904.320028] PACK 0.292 (0.292)		UNPACK 0.052 (0.052)		
[1590617904.320735] Trying camera with id 0
2020-05-27 17:18:24.378 python[1069:22551] alloc
2020-05-27 17:18:24.378 python[1069:22551] query 2
2020-05-27 17:18:24.378 python[1069:22551] release 2
2020-05-27 17:18:24.378 python[1069:22551] ** MyPlugInitializeWithObjectID
2020-05-27 17:18:24.378 python[1069:22551] init
2020-05-27 17:18:24.379 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.379 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.379 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.379 python[1069:22551] Trying to get Surface
2020-05-27 17:18:24.382 python[1069:22551] Found Surface
2020-05-27 17:18:24.383 python[1069:22551] Surface is not in use
2020-05-27 17:18:24.383 python[1069:22551] Surface is 0x140271912999008
2020-05-27 17:18:24.383 python[1069:22551] Driver name is 8 CamTwist
2020-05-27 17:18:24.383 python[1069:22551] <CMVideoFormatDescription 0x7f93998be450 [0x7fff85d9a8c0]> {
	mediaType:'vide' 
	mediaSubType:'BGRA' 
	mediaSpecific: {
		codecType: 'BGRA'		dimensions: 320 x 240 
	} 
	extensions: {{
    CVBytesPerRow = 1280;
    CVFieldCount = 1;
    FormatName = "Component Video - CCIR-601 RGB";
    "com.apple.cmio.format_extension.video.only_has_i_frames" = 1;
}}
}
2020-05-27 17:18:24.383 python[1069:22551] Name CamTwist
2020-05-27 17:18:24.383 python[1069:22551] alloc
2020-05-27 17:18:24.383 python[1069:22551] query 2
2020-05-27 17:18:24.383 python[1069:22551] release 2
2020-05-27 17:18:24.383 python[1069:22551] ** MyPlugInitializeWithObjectID
2020-05-27 17:18:24.383 python[1069:22551] init
2020-05-27 17:18:24.383 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.383 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.383 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.383 python[1069:22551] <CMVideoFormatDescription 0x7f93998c03f0 [0x7fff85d9a8c0]> {
	mediaType:'vide' 
	mediaSubType:'2vuy' 
	mediaSpecific: {
		codecType: '2vuy'		dimensions: 320 x 240 
	} 
	extensions: {{
    CVFieldCount = 1;
    CVImageBufferColorPrimaries = "SMPTE_C";
    CVImageBufferTransferFunction = "ITU_R_709_2";
    CVImageBufferYCbCrMatrix = "ITU_R_601_4";
    FormatName = "Component Video - CCIR-601 uyvy";
    "com.apple.cmio.format_extension.video.only_has_i_frames" = 1;
}}
}
2020-05-27 17:18:24.384 python[1069:22551] Name CamTwist (2VUY)
2020-05-27 17:18:24.389 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.389 python[1069:22551] enog
2020-05-27 17:18:24.389 python[1069:22551] bolg
2020-05-27 17:18:24.389 python[1069:22551] 0
2020-05-27 17:18:24.389 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.389 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.389 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.389 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.389 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.389 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.389 python[1069:22551] sel dnwo
2020-05-27 17:18:24.389 python[1069:22551] scope bolg
2020-05-27 17:18:24.389 python[1069:22551] elt 0
2020-05-27 17:18:24.389 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.389 python[1069:22551] sel dnwo
2020-05-27 17:18:24.389 python[1069:22551] scope bolg
2020-05-27 17:18:24.389 python[1069:22551] elt 0
2020-05-27 17:18:24.389 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.389 python[1069:22551] sel dnwo
2020-05-27 17:18:24.389 python[1069:22551] scope bolg
2020-05-27 17:18:24.389 python[1069:22551] elt 0
2020-05-27 17:18:24.389 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.389 python[1069:22551] sel dnwo
2020-05-27 17:18:24.389 python[1069:22551] scope bolg
2020-05-27 17:18:24.389 python[1069:22551] elt 0
2020-05-27 17:18:24.390 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.390 python[1069:22551] sel dnwo
2020-05-27 17:18:24.390 python[1069:22551] scope bolg
2020-05-27 17:18:24.390 python[1069:22551] elt 0
2020-05-27 17:18:24.390 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.390 python[1069:22551] sel dnwo
2020-05-27 17:18:24.390 python[1069:22551] scope bolg
2020-05-27 17:18:24.390 python[1069:22551] elt 0
2020-05-27 17:18:24.390 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.390 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.390 python[1069:22551] sel dnwo
2020-05-27 17:18:24.390 python[1069:22551] scope bolg
2020-05-27 17:18:24.390 python[1069:22551] elt 0
2020-05-27 17:18:24.390 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.390 python[1069:22551] grrf
2020-05-27 17:18:24.390 python[1069:22551] bolg
2020-05-27 17:18:24.390 python[1069:22551] 0
2020-05-27 17:18:24.390 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.390 python[1069:22551] sel dnwo
2020-05-27 17:18:24.390 python[1069:22551] scope bolg
2020-05-27 17:18:24.390 python[1069:22551] elt 0
2020-05-27 17:18:24.390 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.390 python[1069:22551] grrf
2020-05-27 17:18:24.390 python[1069:22551] bolg
2020-05-27 17:18:24.390 python[1069:22551] 0
2020-05-27 17:18:24.390 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.390 python[1069:22551] trfn
2020-05-27 17:18:24.390 python[1069:22551] bolg
2020-05-27 17:18:24.390 python[1069:22551] 0
2020-05-27 17:18:24.390 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.390 python[1069:22551] trfm
2020-05-27 17:18:24.390 python[1069:22551] bolg
2020-05-27 17:18:24.391 python[1069:22551] 0
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.391 python[1069:22551] trfn
2020-05-27 17:18:24.391 python[1069:22551] bolg
2020-05-27 17:18:24.391 python[1069:22551] 0
2020-05-27 17:18:24.391 python[1069:22551] DN: CamTwist
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.391 python[1069:22551] dulp
2020-05-27 17:18:24.391 python[1069:22551] tpni
2020-05-27 17:18:24.391 python[1069:22551] 0
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.391 python[1069:22551] sel dnwo
2020-05-27 17:18:24.391 python[1069:22551] scope bolg
2020-05-27 17:18:24.391 python[1069:22551] elt 0
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.391 python[1069:22551] enog
2020-05-27 17:18:24.391 python[1069:22551] bolg
2020-05-27 17:18:24.391 python[1069:22551] 0
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.391 python[1069:22551] sel dnwo
2020-05-27 17:18:24.391 python[1069:22551] scope bolg
2020-05-27 17:18:24.391 python[1069:22551] elt 0
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.391 python[1069:22551] sel dnwo
2020-05-27 17:18:24.391 python[1069:22551] scope bolg
2020-05-27 17:18:24.391 python[1069:22551] elt 0
2020-05-27 17:18:24.391 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.391 python[1069:22551] sel dnwo
2020-05-27 17:18:24.391 python[1069:22551] scope bolg
2020-05-27 17:18:24.392 python[1069:22551] elt 0
2020-05-27 17:18:24.392 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.392 python[1069:22551] sel dnwo
2020-05-27 17:18:24.392 python[1069:22551] scope bolg
2020-05-27 17:18:24.392 python[1069:22551] elt 0
2020-05-27 17:18:24.392 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.392 python[1069:22551] sel dnwo
2020-05-27 17:18:24.392 python[1069:22551] scope bolg
2020-05-27 17:18:24.392 python[1069:22551] elt 0
2020-05-27 17:18:24.392 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.392 python[1069:22551] sel dnwo
2020-05-27 17:18:24.392 python[1069:22551] scope bolg
2020-05-27 17:18:24.392 python[1069:22551] elt 0
2020-05-27 17:18:24.392 python[1069:22551] MyPlugObjectSetPropertyData
2020-05-27 17:18:24.392 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.392 python[1069:22551] sel dnwo
2020-05-27 17:18:24.392 python[1069:22551] scope bolg
2020-05-27 17:18:24.392 python[1069:22551] elt 0
2020-05-27 17:18:24.392 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.392 python[1069:22551] grrf
2020-05-27 17:18:24.392 python[1069:22551] bolg
2020-05-27 17:18:24.392 python[1069:22551] 0
2020-05-27 17:18:24.392 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.392 python[1069:22551] sel dnwo
2020-05-27 17:18:24.392 python[1069:22551] scope bolg
2020-05-27 17:18:24.392 python[1069:22551] elt 0
2020-05-27 17:18:24.392 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.392 python[1069:22551] grrf
2020-05-27 17:18:24.392 python[1069:22551] bolg
2020-05-27 17:18:24.393 python[1069:22551] 0
2020-05-27 17:18:24.393 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.393 python[1069:22551] trfn
2020-05-27 17:18:24.393 python[1069:22551] bolg
2020-05-27 17:18:24.393 python[1069:22551] 0
2020-05-27 17:18:24.393 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.393 python[1069:22551] trfm
2020-05-27 17:18:24.393 python[1069:22551] bolg
2020-05-27 17:18:24.393 python[1069:22551] 0
2020-05-27 17:18:24.393 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.393 python[1069:22551] trfn
2020-05-27 17:18:24.393 python[1069:22551] bolg
2020-05-27 17:18:24.393 python[1069:22551] 0
2020-05-27 17:18:24.393 python[1069:22551] DN: CamTwist (2VUY)
2020-05-27 17:18:24.393 python[1069:22551] MyPlugObjectHasProperty
2020-05-27 17:18:24.393 python[1069:22551] dulp
2020-05-27 17:18:24.393 python[1069:22551] tpni
2020-05-27 17:18:24.393 python[1069:22551] 0
2020-05-27 17:18:24.393 python[1069:22551] MyPlugObjectGetPropertyDataSize
2020-05-27 17:18:24.393 python[1069:22551] sel dnwo
2020-05-27 17:18:24.393 python[1069:22551] scope bolg
2020-05-27 17:18:24.393 python[1069:22551] elt 0
2020-05-27 17:18:24.407 python[1069:22551] MyPlugObjectIsPropertySettable
2020-05-27 17:18:24.407 python[1069:22551] MyPlugObjectIsPropertySettable
2020-05-27 17:18:24.407 python[1069:22551] MyPlugObjectIsPropertySettable
2020-05-27 17:18:24.407 python[1069:22551] MyPlugObjectSetPropertyData
[ERROR:0] VIDEOIO(cvCreateCameraCapture_AVFoundation(index)): raised unknown C++ exception!


[1590617904.412160] Camera with id 0 is not available
[1590617904.412196] Trying camera with id 1
2020-05-27 17:18:24.412 python[1069:22551] MyPlugObjectIsPropertySettable
2020-05-27 17:18:24.412 python[1069:22551] MyPlugObjectIsPropertySettable
2020-05-27 17:18:24.412 python[1069:22551] MyPlugObjectIsPropertySettable
2020-05-27 17:18:24.412 python[1069:22551] MyPlugObjectSetPropertyData
[ERROR:0] VIDEOIO(cvCreateCameraCapture_AVFoundation(index)): raised unknown C++ exception!


[1590617904.412868] Camera with id 1 is not available
[1590617904.412898] Trying camera with id 2
[1590617905.791649] Trying camera with id 3
OpenCV: out device of bound (0-2): 3
OpenCV: camera failed to properly initialize!
[1590617905.791817] Camera with id 3 is not available
Traceback (most recent call last):
  File "/Users/PATH/avatarify/afy/camera_selector.py", line 63, in mouse_callback
    if camid < len(cam_frames):
NameError: name 'cam_frames' is not defined
^C[1590618078.333827] recv_worker: user interrupt
[1590618078.333827] send_worker: user interrupt
[1590618078.335333] send_worker exit
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 180, in <module>
[1590618078.336260] recv_worker exit
    cam_id = select_camera(config)
  File "afy/cam_fomm.py", line 131, in select_camera
    cam_id = cam_selector.select_camera(cam_frames, window="CLICK ON YOUR CAMERA")
  File "/Users/PATH/avatarify/afy/camera_selector.py", line 77, in select_camera
    key = cv2.waitKey(10)
KeyboardInterrupt
2020-05-27 17:21:18.427 python[1069:22551] MyPlugTeardown

**Comment by alievk** [comment]
Could you please pull the latest commits and try it again?
There was a stupid bug creeped in one of the earlier commits.

**Comment by inglesuniversal** [comment]
Hello:

I followed your steps... and VOILA .... I was able to see two windows... one to set up the red box and the other one to preview the avatar... Pretty NEAT stuff.

However, once I chose CAMTWIST as video source inside ZOOM. the output would show the previously chosen avatar, but all I got LIVE was a frozen image of the Avatar.

I am using ZOOM: Version: 4.6.12 (20615.0421)

and as suggested on your docs I ran the command to allow the virtual camera no matter which version of ZOOM is running on Mac.

Any ideas how to fix the frozen output video on ZOOM?

Thanks

Hugo

**Comment by karfly** [comment]
Hi, @inglesuniversal!
Your avatar in camtwist is freozen, but the Avatarify window with avatar preview is working well, right?

Can you send a screenshot of your CamTwist settings?

**Comment by inglesuniversal** [comment]
I just fixed it... I restarted the computer once... and I haven't had any issues since then.

Can an MacBook Air 8gb RAM work without the Google Server (remote connection) ?... it takes me about 5 to 10 minutes to set up every day

**Comment by alievk** [comment]
No, Mac is not powerful enough to run the neural network. Ideally you need a gaming PC with a powerful GPU to run it with a good FPS.

In the future we are planning to optimize the neural network run time for Mac and non-CUDA GPUs (AMD).
