### ISSUE TITLE
Unable to start the Google Colab worker

### ISSUE THREAD

**Issue by harpreets** [alievk/avatarify#200]
**Describe the bug**
Unable to start the [Google Colab worker](https://colab.research.google.com/github/alievk/avatarify/blob/master/avatarify.ipynb#scrollTo=8PnArK75mRqx)

**To Reproduce**
Ran through the Google Colab steps, until `Start the worker` item #2. At this step, I get an unable to start the worker error. 

**Info (please complete the following information):**
 - OS (Mac): 

**Logs**
Worker failed to start
[1591223276.356718] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 160, in <module>
    from afy import predictor_worker
  File "/content/avatarify/afy/predictor_worker.py", line 1, in <module>
    from predictor_local import PredictorLocal
  File "/content/avatarify/afy/predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules'

**Comment by alievk** [comment]
1. Check that `fomm` folder is in `/content/avatarify`
2. If not, check the errors during the installation. Is `git` available from the command line?
