### ISSUE TITLE
Runtime error: storage has wrong size: expected 0 got 256

### ISSUE THREAD

**Issue by AmbiTyga** [alievk/avatarify#201]
After following the instruction for windows I ran the batch file `run_windows.bat`
I got the `Runtime error: storage has wrong size: expected 0 got 256`

System Info
 - OS (e.g., Linux): Windows
 - GPU model: Nvidia GTX 1080 Ti
- Any other relevant information: My user file directory has space in it (C:\Users\Ambesh Shekhar\)

On Windows (Miniconda prompt) run:
conda activate avatarify
conda info
conda list
:: Environment info
set | findstr /I "CUDA CONDA Python" | findstr /V "Path"
echo %PATH:;=&echo.%

On Linux/Mac environment info:
conda activate avatarify 
`(avatarify) E:\EDU\avatarify>`
conda info
```
     active environment : avatarify
    active env location : C:\Users\Ambesh Shekhar\.conda\envs\avatarify
            shell level : 1
       user config file : C:\Users\Ambesh Shekhar\.condarc
 populated config files : C:\Users\Ambesh Shekhar\.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.1
       base environment : C:\ProgramData\Miniconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\Ambesh Shekhar\.conda\pkgs
                          C:\Users\Ambesh Shekhar\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Ambesh Shekhar\.conda\envs
                          C:\ProgramData\Miniconda3\envs
                          C:\Users\Ambesh Shekhar\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
conda list:
```
# packages in environment at C:\Users\Ambesh Shekhar\.conda\envs\avatarify:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
blosc                     1.18.1               h6538335_0    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               0.5.3                    pypi_0    pypi
cuda100                   1.0                           0    pytorch
cycler                    0.10.0                   pypi_0    pypi
dask                      0.18.2                   pypi_0    pypi
decorator                 4.3.0                    pypi_0    pypi
face-alignment            1.0.0                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.9                      pypi_0    pypi
imageio                   2.3.0                    pypi_0    pypi
intel-openmp              2020.1                      216
jpeg                      9b                   hb83a4c4_2
kiwisolver                1.0.1                    pypi_0    pypi
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.1.0                h56a325e_1
lz4-c                     1.9.2                h62dcd97_0
matplotlib                2.2.2                    pypi_0    pypi
mkl                       2020.1                      216
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.1            py37h47e9c7a_0
msgpack                   1.0.0                    pypi_0    pypi
msgpack-numpy             0.4.5                    pypi_0    pypi
networkx                  2.1                      pypi_0    pypi
ninja                     1.9.0            py37h74a9793_0
numpy                     1.15.0                   pypi_0    pypi
olefile                   0.46                     py37_0
opencv-python             4.2.0.34                 pypi_0    pypi
openssl                   1.1.1g               he774522_0    conda-forge
pandas                    0.23.4                   pypi_0    pypi
pillow                    6.2.2                    pypi_0    pypi
pip                       20.0.2                   py37_3
pycparser                 2.18                     pypi_0    pypi
pyfakewebcam              0.1.0                    pypi_0    pypi
pygit                     0.1                      pypi_0    pypi
pyparsing                 2.2.0                    pypi_0    pypi
python                    3.7.7                h81c818b_4
python-blosc              1.7.0            py37he774522_0
python-dateutil           2.7.3                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.0.0           py3.7_cuda100_cudnn7_1  [cuda100]  pytorch
pytz                      2018.5                   pypi_0    pypi
pywavelets                0.5.2                    pypi_0    pypi
pyyaml                    5.1                      pypi_0    pypi
pyzmq                     19.0.0                   pypi_0    pypi
requests                  2.23.0                   pypi_0    pypi
scikit-image              0.14.0                   pypi_0    pypi
scikit-learn              0.19.2                   pypi_0    pypi
scipy                     1.1.0                    pypi_0    pypi
setuptools                46.4.0                   py37_0
six                       1.11.0                   pypi_0    pypi
sqlite                    3.31.1               h2a8f88b_1
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                    pypi_0    pypi
torchvision               0.2.1                      py_2    pytorch
tqdm                      4.24.0                   pypi_0    pypi
urllib3                   1.25.9                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_2
wheel                     0.34.2                   py37_0
wincertstore              0.2                      py37_0
xz                        5.2.5                h62dcd97_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.4                ha9fde0e_3
```
echo $PYTHONPATH:
`$PYTHONPATH`
echo $PATH:
`$PATH`
```
[1591283113.796947] Loading Predictor
C:\Users\Ambesh Shekhar\.conda\envs\avatarify\lib\site-packages\dask\config.py:129: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
E:\EDU\avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 177, in <module>
    **predictor_args
  File "E:\EDU\avatarify\afy\predictor_local.py", line 27, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "C:\Users\Ambesh Shekhar\.conda\envs\avatarify\lib\site-packages\face_alignment\api.py", line 66, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "C:\Users\Ambesh Shekhar\.conda\envs\avatarify\lib\site-packages\face_alignment\detection\sfd\sfd_detector.py", line 44, in __init__
    self.face_detector.load_state_dict(torch.load(path_to_detector))
  File "C:\Users\Ambesh Shekhar\.conda\envs\avatarify\lib\site-packages\torch\serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\Ambesh Shekhar\.conda\envs\avatarify\lib\site-packages\torch\serialization.py", line 545, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 0 got 256
```

**Comment by alievk** [comment]
Looks like `face_alignment` was trying to load the network checkpoint and it was corrupted probably during the download. You may have noticed that when first run `run_windows.bat`
The easiest solution would be running the install script again to initiate the download again.

**Comment by AmbiTyga** [comment]
Actually I did that, more than one time. Still the results were same.

**Comment by alievk** [comment]
You have to look here
```
"C:\Users\Ambesh Shekhar\.conda\envs\avatarify\lib\site-packages\face_alignment\detection\sfd\sfd_detector.py", line 44, in __init__
    self.face_detector.load_state_dict(torch.load(path_to_detector))
```
Just `print(path_to_detector)` and it will show you the path to the checkpoint and you can delete it to make it download it again.
