### ISSUE TITLE
Can you run this without Conda?

### ISSUE THREAD

**Issue by amitrege** [alievk/avatarify#203]
Hi, 
I'm trying to run this on my Mac using the Colab notebook. I got the following error when running run_mac.sh: 
<pre>./run_mac.sh: line 7: conda: command not found
./run_mac.sh:` line 7: /etc/profile.d/conda.sh: No such file or directory
./run_mac.sh: line 8: conda: command not found
[1591468523.220366] Loading Predictor
Process send_process:
Process recv_process:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/amit/dev-work/avatarify/afy/predictor_remote.py", line 135, in send_worker
    sender.connect(address)
  File "zmq/backend/cython/socket.pyx", line 583, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/amit/dev-work/avatarify/afy/predictor_remote.py", line 170, in recv_worker
    receiver.connect(address)
  File "zmq/backend/cython/socket.pyx", line 583, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
</pre>

I'm assuming the issue is due to not having Conda installed locally. Is there any way to get around this? The README does not mention Conda as a dependency and I do not want to install extra stuff just for a single use case.

Thanks!

**Comment by alievk** [comment]
The readme actually says you have to install [Mini]conda.
If you don't want to install conda you can use python environment:
```
cd /path/to/avatarify
python3.7 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```
