### ISSUE TITLE
YAML Load Warning

### ISSUE THREAD

**Issue by rayyan565** [alievk/avatarify#219]
Hi!
I am trying to use avatarify on my Windows PC and have followed the steps mentioned. On step 6 after I run 'run_windows.bat' I am receiving the following error:

(base) C:\Users\ray\avatarify>run_windows.bat
[1592074221.483374] Loading Predictor
C:\Users\ray\avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 195, in <module>
    **predictor_args
  File "C:\Users\ray\avatarify\afy\predictor_local.py", line 26, in __init__
    self.generator, self.kp_detector = self.load_checkpoints()
  File "C:\Users\ray\avatarify\afy\predictor_local.py", line 44, in load_checkpoints
    checkpoint = torch.load(self.checkpoint_path, map_location=self.device)
  File "C:\Users\ray\miniconda3\envs\avatarify\lib\site-packages\torch\serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\ray\miniconda3\envs\avatarify\lib\site-packages\torch\serialization.py", line 545, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 20239023 more bytes. The file might be corrupted.

I tried to disable the warning by editing the code with: yaml.load(input, Loader=yaml.FullLoader)
but it did not work.

Any help would be appreciated.
Thanks

**Comment by alievk** [comment]
This is due to corrupted checkpoint file. Please try to download it again.

**Comment by rayyan565** [comment]
Thanks. That resolved the problem.
