### ISSUE TITLE
Error on using Remote GPU function

### ISSUE THREAD

**Issue by JameLeung** [alievk/avatarify#244]
Have Tried to run the system but once the client try to sending the message. The server hangs 

Here is the screen dump for the Client side and Server side.

**Client Side - Linux Platform**
(base) [avatarify@nb01 avatarify]$ ./run.sh --is-client --in-addr tcp://<IP>:5557 --out-addr tcp://<IP>:5558
[1594223982.975090] Loading Predictor
[1594223982.999439] Sending to tcp://<IP>:5557
[1594223983.000886] SEND 0.205 (0.205)		
[1594223983.000978] Receiving from tcp://<IP>:5558

(wait forever)

**Server Side - Linux System**
(avatarify) avatarify@dl01:~/avatarify$ bash run.sh --is-worker
Creating virtual camera /dev/video9 (sudo privelege required)
[1594223977.850894] Loading Predictor
[1594223978.757580] Receiving on port 5557
[1594223978.762318] Sending on port 5558
[1594223979.759377] recv timeout
[1594223979.763998] send queue empty
[1594223980.760709] recv timeout
[1594223980.765346] send queue empty
[1594223981.762033] recv timeout
[1594223981.766704] send queue empty
[1594223982.762187] recv timeout
[1594223982.768054] send queue empty
[1594223983.044195] RECV 280.014 (280.014)		
[1594223983.045859] working on {'name': '__init__', 'critical': True, 'id': 0}
/home/avatarify/avatarify/afy/predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[1594223983.769434] send queue empty
[1594223983.963072] predictor_worker error
Traceback (most recent call last):
  File "/home/avatarify/avatarify/afy/predictor_worker.py", line 144, in predictor_worker
    predictor = PredictorLocal(*predictor_args[0], **predictor_args[1])
  File "/home/avatarify/avatarify/afy/predictor_local.py", line 26, in __init__
    self.generator, self.kp_detector = self.load_checkpoints()
  File "/home/avatarify/avatarify/afy/predictor_local.py", line 38, in load_checkpoints
    generator.to(self.device)
  File "/home/avatarify/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/home/avatarify/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/avatarify/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/avatarify/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/avatarify/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/avatarify/miniconda3/envs/avatarify/lib/python3.7/site-packages/torch/nn/modules/module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: out of memory
[1594223983.969252] predictor_worker exit
[1594223984.045797] recv timeout
[1594223984.045923] recv_worker exit
[1594223984.770804] send queue empty
[1594223984.770914] send_worker exit

**Comment by mintmaker** [comment]
It's a CUDA memory error. That means you have not enough VRAM on your server to run the Deepfake-model.
Sorry, you can't run avatarify on that server.
