### ISSUE TITLE
could not insert 'v4l2loopback': Operation not permitted

### ISSUE THREAD

**Issue by everm1n** [alievk/avatarify#258]
**Describe the bug**

v4l2loopback does not work: operation is not permitted. 

**To Reproduce**

running the run.sh on Ubuntu kernel 5.4.0-40-generic

**Info (please complete the following information):**
 - OS (e.g., Linux): Ubuntu 20.04 LTS 5.4.0-40-generic
 - GPU model: Nvidia 1060 6 gb ram
 sudo apt install nvidia-utils-390         # version 390.138-0ubuntu0.20.04.1, or
sudo apt install nvidia-utils-440         # version 440.100-0ubuntu0.20.04.1
sudo apt install nvidia-340               # version 340.108-0ubuntu2
sudo apt install nvidia-utils-435         # version 435.21-0ubuntu7
sudo apt install nvidia-utils-418-server  # version 418.152.00-0ubuntu0.20.04.1
sudo apt install nvidia-utils-440-server  # version 440.95.01-0ubuntu0.20.04.1

 - Any other relevant information: 

     active environment : avatarify
    active env location : /home/alex/miniconda3/envs/avatarify
            shell level : 2
       user config file : /home/alex/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.31
       base environment : /home/alex/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/alex/miniconda3/pkgs
                          /home/alex/.conda/pkgs
       envs directories : /home/alex/miniconda3/envs
                          /home/alex/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Linux/5.4.0-40-generic ubuntu/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
blosc                     1.20.0               he1b5a44_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37he30daa8_1  
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               0.5.3                    pypi_0    pypi
cuda100                   1.0                           0    pytorch
cycler                    0.10.0                   pypi_0    pypi
dask                      0.18.2                   pypi_0    pypi
decorator                 4.3.0                    pypi_0    pypi
face-alignment            1.0.0                    pypi_0    pypi
freetype                  2.10.2               h5ab3b9f_0  
idna                      2.10                     pypi_0    pypi
imageio                   2.3.0                    pypi_0    pypi
intel-openmp              2020.1                      217  
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.0.1                    pypi_0    pypi
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
lz4-c                     1.9.2                he6710b0_1  
matplotlib                2.2.2                    pypi_0    pypi
mkl                       2020.1                      217  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.1.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
msgpack                   1.0.0                    pypi_0    pypi
msgpack-numpy             0.4.5                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
networkx                  2.1                      pypi_0    pypi
ninja                     1.10.0           py37hfd86e86_0  
numpy                     1.15.0                   pypi_0    pypi
olefile                   0.46                     py37_0  
opencv-python             4.2.0.34                 pypi_0    pypi
openssl                   1.1.1g               h516909a_1    conda-forge
pandas                    0.23.4                   pypi_0    pypi
pillow                    6.2.2                    pypi_0    pypi
pip                       20.1.1                   py37_1  
pycparser                 2.18                     pypi_0    pypi
pyfakewebcam              0.1.0                    pypi_0    pypi
pygit                     0.1                      pypi_0    pypi
pyparsing                 2.2.0                    pypi_0    pypi
python                    3.7.7                hcff3b4d_5  
python-blosc              1.7.0            py37h7b6447c_0  
python-dateutil           2.7.3                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.0.0           py3.7_cuda10.0.130_cudnn7.4.1_1  [cuda100]  pytorch
pytz                      2018.5                   pypi_0    pypi
pywavelets                0.5.2                    pypi_0    pypi
pyyaml                    5.1                      pypi_0    pypi
pyzmq                     19.0.0                   pypi_0    pypi
readline                  8.0                  h7b6447c_0  
requests                  2.23.0                   pypi_0    pypi
scikit-image              0.14.0                   pypi_0    pypi
scikit-learn              0.19.2                   pypi_0    pypi
scipy                     1.1.0                    pypi_0    pypi
setuptools                49.2.0                   py37_0  
six                       1.11.0                   pypi_0    pypi
sqlite                    3.32.3               h62c20be_0  
tk                        8.6.10               hbc83047_0  
toolz                     0.9.0                    pypi_0    pypi
torchvision               0.2.1                      py_2    pytorch
tqdm                      4.24.0                   pypi_0    pypi
urllib3                   1.25.10                  pypi_0    pypi
wheel                     0.34.2                   py37_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  

/home/alex/miniconda3/envs/avatarify/bin:/home/alex/miniconda3/condabin:/home/alex/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Screenshots**

**Logs**

'''(avatarify) alex@alex-GL703VM:~/Downloads/avatarify$ bash run.sh 
Creating virtual camera /dev/video6 (sudo privelege required)
modprobe: ERROR: could not insert 'v4l2loopback': Operation not permitted
[1596578409.127639] Loading Predictor
/home/alex/Downloads/avatarify/afy/predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)

--- Make sure the v4l2loopback kernel module is loaded ---
sudo modprobe v4l2loopback devices=1

Traceback (most recent call last):
  File "afy/cam_fomm.py", line 221, in <module>
    stream = pyfakewebcam.FakeWebcam(f'/dev/video{opt.virt_cam}', *stream_img_size)
  File "/home/alex/miniconda3/envs/avatarify/lib/python3.7/site-packages/pyfakewebcam/pyfakewebcam.py", line 31, in __init__
    raise FileNotFoundError('device does not exist: {}'.format(video_device))
FileNotFoundError: device does not exist: /dev/video6
FATAL: exception not rethrown
run.sh: line 149: 18401 Aborted                 (core dumped) python afy/cam_fomm.py --config $FOMM_CONFIG --checkpoint $FOMM_CKPT --virt-cam $CAMID_VIRT --relative --adapt_scale $@'''

**Comment by mintmaker** [comment]
Same as in: https://github.com/umlaeute/v4l2loopback/issues/306 and #43 
Secure Boot is probably enabled, you could try to disable it in the BIOS (just google it up) or try to run [these](https://github.com/umlaeute/v4l2loopback/issues/306#issuecomment-626829177l) steps.
After that try to run avatarify again (WITHOUT re-running the `install.sh` ).

**Comment by MitalPattani** [comment]
@alievk is it possible to run this in Secure Boot, I am getting the exact same error!

**Comment by alievk** [comment]
I don't have a solution for that, sorry.

**Comment by AvverbioPronome** [comment]
> @alievk is it possible to run this in Secure Boot, I am getting the exact same error!

I had the same issue with some other software, once I realized from this discussion it was secureboot that wasn't allowing me to do what I wanted, it was easy enough to do what I did all other times this happened, following this tutorial: https://gist.github.com/dop3j0e/2a9e2dddca982c4f679552fc1ebb18df

**Comment by whatisor** [comment]
sudo apt install v4l2loopback-dkms
Follow guide while installing, it will requires you to create  a safeboot Password
Create any password you want and REMEMBER it.
 Then reboot, safeboot will show menu for Enroll MOK
Select Enroll => New
Enter password registered while installing dkms

After reboot, you will be able to run modprobe to create virtual device.
