### ISSUE TITLE
unable to run windows

### ISSUE THREAD

**Issue by Algoroxyolo** [alievk/avatarify#263]
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 193, in <module>
    from afy import predictor_local
  File "E:\论文\The_University_of_Algoras\acad\revisions\avatarify-master\afy\predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules.keypoint_detector'; 'modules' is not a package

**Comment by emrekaplanek** [comment]
same error , is there any solution?

**Comment by JohanAR** [comment]
It's difficult to say what is causing it for you without having your full logs, both from installation and when trying to run it. Often the cause is that the user is not following the install instructions, and is not running Avatarify / Python in a properly set up Conda environment.

I've seen other reports of users having problems if they have unicode characters in the file path, so that could be a possibility

So first please go through the installation once again, and make sure you haven't missed some step. If it's still not working, create a new issue, and fill out the default template with the required information, and someone will hopefully be able to help you
