### ISSUE TITLE
Was working fine, now very poorly

### ISSUE THREAD

**Issue by JohnPrager** [alievk/avatarify#277]
I installed it all according to the video a few days ago, so have the latest everything.  Windows 10, Geforce 1650 super.  Everything worked fine.  Since that time, I made no changes to the install, did nothing low-level or configuration-oriented on my system, just some work on a presentation.  

Now when I run avatarify if loads and appears to run, but is very unresponsive, I don't mean with a lag but the magnitude of the response.  I move my eyebrows or mouth, and there is the barest flicker of a change in the avatar.  I turn my face to the left or right and the avatar face turns a little (not as much) and gets blurry quickly.

Using the camera in Zoom, out of avatarify, I got a screenshot of myself to use as an avatar, so that now the avatar is to all intents and purposes identical to the image of me in the cam window, but it was no better.  

It seems as if the gain control is turned way down - don't know if there is such a thing, but that is the effect.  If this was the program's behavior out of the box, I would think that that's just the way it is, but as I said at the top, it used to work just fine.  This may be related to problem #215.  Any idea?  Thanks.

**Comment by JohnPrager** [comment]
It seems like the developer has claimed his 15 minutes of fame and left town, but while this is disturbing, I also think that my situation is a very interesting logical problem that maybe someone out there can figure out.  It may not need any knowledge of the code itself.
To summarize, I got the program working fine, so I clearly have a correct installation and requisite hardware.  Then a few days later it went into a scarcely-responsive mode - still working, but looked like it was drugged.  Then, and this is new info, it started working again - for one day, about.  Then it went back to drugged mode.  I have been doing nothing on my machine all this time other than running office-type apps.  No changes to hardware, drivers, etc.  Same location of camera, same lighting etc.  Rebooting makes no difference.  This seems like a real mystery.  I want to use this in an AI class I'll be teaching later this month, but obviously I can't until I get this straightened out.
I can't even think of what KIND of thing may be causing this mis-behaviour.  Any ideas, anyone?  Thanks.

**Comment by alievk** [comment]
Sorry for being absent, I have another project which occupies all my time. 

I saw the screencast of your issue in Slack and it looks very exotic.

**Comment by JohnPrager** [comment]
Ali,

Well thank you for replying.  As you can imagine, this is quite
frustrating, especially as it used to work.  Since I'm a problem-solver at
heart, there is the other motivation just to treat it as a puzzle needing
to be solved.  So far, no luck.

I did all the obvious things, like checking the NVIDIA drivers were up to
date, and reinstalling miniconda and avatarify, but to no avail.  What's so
mysterious is that it sort-of works.

The fact that it reacted to gross movements of my head, but not (or
scarcely) to mouth and eye movements, reminded me of this:
https://arxiv.org/pdf/1812.04948.pdf.

Are you familiar with this? I know the mechanism is not the same, but in
both this paper and avatarify the coarse-grained features are behaving
differently from the fine-grained ones.

Other than that, I'm all out of ideas. Do you think it might make a
difference if I tried using the Ubuntu simulation that Windows 10 offers?

Thanks,

John.

**Comment by alievk** [comment]
I'm not sure it would make a difference if you use Ubuntu simulation.

**Comment by JohnPrager** [comment]
Hi Ali,

I posted an update a while ago, but maybe that went astray.  I ended up
fixing the problem by re-downloading the weights file.  This is very
bizarre, since the original file was not touched (at least according to the
operating system, the last-modified time is the same as the original
download time).   You'd think that if the weights file got corrupted, there
would be format problems that would prevent it from loading.  As it
happens, corrupted weights is consistent with my earlier message that it
looked like the fine and coarse features were being treated differently.

Anyway, problem solved.  You might want to store this incident away in the
back of your memory in case anybody else reports it, but it probably won't
happen!

Thanks for your help,

John

**Comment by alievk** [comment]
I would definitely remember this case, thank you!

**Comment by Wire147** [comment]
hi aliev i am stuck at the predictor loading page. one camera pops up after a really long time of my cam being on and it just quits almost immediately

Traceback (most recent call last):
  File "afy/cam_fomm.py", line 316, in <module>
    out = predictor.predict(frame)
  File "C:\Users\omas\avatarify-python\afy\predictor_local.py", line 104, in predict
    use_relative_jacobian=self.relative, adapt_movement_scale=self.adapt_movement_scale)
  File "C:\Users\omas\avatarify-python\afy\predictor_local.py", line 28, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`
