### ISSUE TITLE
Worker on collab notebook crashes

### ISSUE THREAD

**Issue by Horkovsky** [alievk/avatarify#280]
**Describe the bug**
After connecting to the google collab notebook, server worker crushing with pickle deserialization error ```UnpicklingError```

Workers start correct, but fails after connect. 

**To Reproduce**
Reproducing only on google collab notebook. On different physical machines as client and server, works correct. 

* Run google collab notebook with ngrok tunnel
* run client with --is-client option and correct ngrok addresses

**Info (please complete the following information):**
Patforms - Windows, Linux
GPU - Remote Google Collab

 - Any other relevant information: 

client conda config
```      active environment : avatarify
    active env location : C:\Users\user\miniconda3\envs\avatarify
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\user\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\user\miniconda3\pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\miniconda3\envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
**Screenshots**

**Logs**

Starting the workers by cell and check processes

```
root        1490 42.0  2.1 2079564 292580 ?      S    14:43   0:01 python3 afy/cam_fomm.py --config fomm/config/vox-adv-256.yaml --checkpoint vox-adv-cpk.pth.tar --virt-cam 9 --relative --adapt_scale --is-worker --in-port 5557 --out-port 5558 --no-stream
root        1502  0.0  1.1 2087760 154880 ?      Sl   14:43   0:00 python3 afy/cam_fomm.py --config fomm/config/vox-adv-256.yaml --checkpoint vox-adv-cpk.pth.tar --virt-cam 9 --relative --adapt_scale --is-worker --in-port 5557 --out-port 5558 --no-stream
root        1505  0.0  1.1 2079564 152140 ?      S    14:43   0:00 python3 afy/cam_fomm.py --config fomm/config/vox-adv-256.yaml --checkpoint vox-adv-cpk.pth.tar --virt-cam 9 --relative --adapt_scale --is-worker --in-port 5557 --out-port 5558 --no-stream
root        1506  0.0  1.1 2087760 154884 ?      Sl   14:43   0:00 python3 afy/cam_fomm.py --config fomm/config/vox-adv-256.yaml --checkpoint vox-adv-cpk.pth.tar --virt-cam 9 --relative --adapt_scale --is-worker --in-port 5557 --out-port 5558 --no-stream
Worker started
```

starting the client 
```
run_windows.bat --is-client --in-addr tcp://0.tcp.ap.ngrok.io:10312 --out-addr tcp://0.tcp.ap.ngrok.io:13952
```
or
```
bash run.sh --is-client --in-addr tcp://0.tcp.ap.ngrok.io:10312 --out-addr tcp://0.tcp.ap.ngrok.io:13952
```

Checking `/tmp/run.txt`
``` 
Worker failed to start
[1600004319.755390] Loading Predictor
/content/avatarify/afy/predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[1600007559.409050] predictor_worker error
Traceback (most recent call last):
  File "/content/avatarify/afy/predictor_worker.py", line 144, in predictor_worker
    predictor = PredictorLocal(*predictor_args[0], **predictor_args[1])
  File "/content/avatarify/afy/predictor_local.py", line 26, in __init__
    self.generator, self.kp_detector = self.load_checkpoints()
  File "/content/avatarify/afy/predictor_local.py", line 44, in load_checkpoints
    checkpoint = torch.load(self.checkpoint_path, map_location=self.device)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
[1600007559.409931] predictor_worker exit
[1600004321.285986] Receiving on port 5557
[1600007559.585374] recv_worker exit
[1600004321.293875] Sending on port 5558
[1600007559.933528] send_worker exit
```

**Comment by alievk** [comment]
Whoops! I've moved the checkpoint to another S3 bucket and forgot to fix the link in the `download_data.sh` script. Fixed. Please start over.

**Comment by Horkovsky** [comment]
Thanks! All works now.

**Comment by Code0x58** [comment]
A note on this: the Dockerfile references the commit `v0.1-docker` which won't work any more because of this, but it can be overridden with a build line like `docker build --build-arg=AVATARIFY_COMMIT=master -t avatarify .` before doing the `./run.sh --docker`
