### ISSUE TITLE
Cannot open camera linux

### ISSUE THREAD

**Issue by Mark-papi** [alievk/avatarify#305]
it was working, but for some reason its not now.

**here are the bugs:
1605262753.258474] Loading Predictor
/home/sollekram/avatarify/afy/predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 203, in <module>
    cap = VideoCaptureAsync(cam_id)
  File "/home/sollekram/avatarify/afy/videocaptureasync.py", line 17, in __init__
    raise RuntimeError("Cannot open camera")
RuntimeError: Cannot open camera**

**Comment by Mark-papi** [comment]
I solved it i reinstall everything
