### ISSUE TITLE
Module not found and error red text (Command Errored)

### ISSUE THREAD

**Issue by leksfor1** [alievk/avatarify#337]
How can i fix this?

tificates-2020.10.14-he931aee_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main::certifi-2020.12.5-py37h9f7~ --> anaconda::certif
i-2020.6.20-py37_0
  openssl              pkgs/main::openssl-1.1.1i-hc431981_0 --> anaconda::openss
l-1.1.1h-he774522_0

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Cloning into 'fomm'...
remote: Enumerating objects: 211, done.

Receiving objects: 100% (211/211), 58.16 MiB | 221.00 KiB/s, done.
Resolving deltas: 100% (108/108), done.
Updating files: 100% (44/44), done.
WARNING: --use-feature=2020-resolver no longer has any effect, since it is now t
he default dependency resolver in pip. This will become an error in pip 21.0.
Collecting cloudpickle==0.5.3
  Using cached cloudpickle-0.5.3-py2.py3-none-any.whl (13 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting dask==0.18.2
  Using cached dask-0.18.2-py2.py3-none-any.whl (645 kB)
Collecting decorator==4.3.0
  Using cached decorator-4.3.0-py2.py3-none-any.whl (9.2 kB)
Collecting face-alignment==1.0.0
  Using cached face_alignment-1.0.0-py2.py3-none-any.whl (22 kB)
Requirement already satisfied: numpy in c:\users\kim jong jon\.conda\envs\avatar
ify\lib\site-packages (from face-alignment==1.0.0->-r requirements.txt (line 30)
) (1.15.0)
Collecting imageio==2.3.0
  Using cached imageio-2.3.0-py2.py3-none-any.whl (3.3 MB)
Collecting kiwisolver==1.0.1
  Using cached kiwisolver-1.0.1-cp37-none-win32.whl (44 kB)
Requirement already satisfied: setuptools in c:\users\kim jong jon\.conda\envs\a
vatarify\lib\site-packages (from kiwisolver==1.0.1->-r requirements.txt (line 7)
) (51.0.0.post20201207)
Collecting matplotlib==2.2.2
  Using cached matplotlib-2.2.2-cp37-cp37m-win32.whl (8.5 MB)
Collecting msgpack-numpy==0.4.5
  Using cached msgpack_numpy-0.4.5-py2.py3-none-any.whl (6.1 kB)
Collecting networkx==2.1
  Using cached networkx-2.1-py2.py3-none-any.whl
Collecting opencv-python==4.2.0.34
  Using cached opencv_python-4.2.0.34-cp37-cp37m-win32.whl (24.2 MB)
Collecting pandas==0.23.4
  Using cached pandas-0.23.4-cp37-cp37m-win32.whl (6.8 MB)
Collecting Pillow==6.2.2
  Using cached Pillow-6.2.2-cp37-cp37m-win32.whl (1.8 MB)
Collecting pycparser==2.18
  Using cached pycparser-2.18-py2.py3-none-any.whl
Collecting pyfakewebcam==0.1.0
  Using cached pyfakewebcam-0.1.0-py3-none-any.whl
Collecting pygit==0.1
  Using cached pygit-0.1-py3-none-any.whl
Collecting pyparsing==2.2.0
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl (56 kB)
Collecting python-dateutil==2.7.3
  Using cached python_dateutil-2.7.3-py2.py3-none-any.whl (211 kB)
Collecting pytz==2018.5
  Using cached pytz-2018.5-py2.py3-none-any.whl (510 kB)
Collecting PyWavelets==0.5.2
  Using cached PyWavelets-0.5.2-cp37-none-win32.whl (4.1 MB)
Collecting PyYAML==5.1
  Using cached PyYAML-5.1-cp37-cp37m-win32.whl (195 kB)
Collecting pyzmq==19.0.0
  Using cached pyzmq-19.0.0-cp37-cp37m-win32.whl (903 kB)
Collecting requests==2.23
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kim jong jon\.cond
a\envs\avatarify\lib\site-packages (from requests==2.23->-r requirements.txt (li
ne 29)) (2020.6.20)
Collecting scikit-image==0.14.0
  Using cached scikit_image-0.14.0-cp37-none-win32.whl (23.9 MB)
Collecting scikit-learn==0.19.2
  Using cached scikit_learn-0.19.2-cp37-cp37m-win32.whl (3.9 MB)
Collecting scipy==1.1.0
  Using cached scipy-1.1.0-cp37-none-win32.whl (26.1 MB)
Collecting six==1.11.0
  Using cached six-1.11.0-py2.py3-none-any.whl (10 kB)
Collecting toolz==0.9.0
  Using cached toolz-0.9.0-py3-none-any.whl
Collecting tqdm==4.24.0
  Using cached tqdm-4.24.0-py2.py3-none-any.whl (43 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting dask[array]>=0.9.0
  Using cached dask-2020.12.0-py3-none-any.whl (884 kB)
  Using cached dask-2.30.0-py3-none-any.whl (848 kB)
  Using cached dask-2.29.0-py3-none-any.whl (847 kB)
  Using cached dask-2.28.0-py3-none-any.whl (848 kB)
  Using cached dask-2.27.0-py3-none-any.whl (843 kB)
  Using cached dask-2.26.0-py3-none-any.whl (843 kB)
  Using cached dask-2.25.0-py3-none-any.whl (834 kB)
  Using cached dask-2.24.0-py3-none-any.whl (834 kB)
  Using cached dask-2.23.0-py3-none-any.whl (831 kB)
  Using cached dask-2.22.0-py3-none-any.whl (828 kB)
  Using cached dask-2.21.0-py3-none-any.whl (826 kB)
  Using cached dask-2.20.0-py3-none-any.whl (826 kB)
  Using cached dask-2.19.0-py3-none-any.whl (824 kB)
  Using cached dask-2.18.1-py3-none-any.whl (823 kB)
  Using cached dask-2.18.0-py3-none-any.whl (822 kB)
  Using cached dask-2.17.2-py3-none-any.whl (813 kB)
  Using cached dask-2.17.1-py3-none-any.whl (813 kB)
  Using cached dask-2.17.0-py3-none-any.whl (812 kB)
  Using cached dask-2.16.0-py3-none-any.whl (802 kB)
  Using cached dask-2.15.0-py3-none-any.whl (799 kB)
  Using cached dask-2.14.0-py3-none-any.whl (794 kB)
  Using cached dask-2.13.0-py3-none-any.whl (791 kB)
  Using cached dask-2.12.0-py3-none-any.whl (789 kB)
  Using cached dask-2.11.0-py3-none-any.whl (785 kB)
  Using cached dask-2.10.1-py3-none-any.whl (783 kB)
  Using cached dask-2.10.0-py3-none-any.whl (783 kB)
  Using cached dask-2.9.2-py3-none-any.whl (780 kB)
  Using cached dask-2.9.1-py3-none-any.whl (772 kB)
  Using cached dask-2.9.0-py3-none-any.whl (770 kB)
  Using cached dask-2.8.1-py3-none-any.whl (769 kB)
  Using cached dask-2.8.0-py3-none-any.whl (767 kB)
  Using cached dask-2.7.0-py3-none-any.whl (765 kB)
  Using cached dask-2.6.0-py3-none-any.whl (760 kB)
  Using cached dask-2.5.2-py3-none-any.whl (760 kB)
  Using cached dask-2.5.0-py3-none-any.whl (759 kB)
  Using cached dask-2.4.0-py3-none-any.whl (766 kB)
  Using cached dask-2.3.0-py3-none-any.whl (763 kB)
  Using cached dask-2.2.0-py3-none-any.whl (757 kB)
  Using cached dask-2.1.0-py3-none-any.whl (763 kB)
  Using cached dask-2.0.0-py3-none-any.whl (760 kB)
  Using cached dask-1.2.2-py2.py3-none-any.whl (717 kB)
  Using cached dask-1.2.1-py2.py3-none-any.whl (714 kB)
  Using cached dask-1.2.0-py2.py3-none-any.whl (711 kB)
  Using cached dask-1.1.5-py2.py3-none-any.whl (708 kB)
  Using cached dask-1.1.4-py2.py3-none-any.whl (704 kB)
  Using cached dask-1.1.3-py2.py3-none-any.whl (703 kB)
  Using cached dask-1.1.2-py2.py3-none-any.whl (704 kB)
  Using cached dask-1.1.1-py2.py3-none-any.whl (701 kB)
  Using cached dask-1.1.0-py2.py3-none-any.whl (699 kB)
  Using cached dask-1.0.0-py2.py3-none-any.whl (685 kB)
  Using cached dask-0.20.2-py2.py3-none-any.whl (686 kB)
  Using cached dask-0.20.1-py2.py3-none-any.whl (686 kB)
  Using cached dask-0.20.0-py2.py3-none-any.whl (684 kB)
  Using cached dask-0.19.4-py2.py3-none-any.whl (674 kB)
  Using cached dask-0.19.3-py2.py3-none-any.whl (671 kB)
  Using cached dask-0.19.2-py2.py3-none-any.whl (657 kB)
  Using cached dask-0.19.1-py2.py3-none-any.whl (655 kB)
  Using cached dask-0.19.0-py2.py3-none-any.whl (653 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting msgpack>=0.5.2
  Using cached msgpack-1.0.2-cp37-cp37m-win32.whl (61 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\KIM JONG JON\.conda\envs\avatarify\python.exe' -u -c 'impo
rt sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KIMJON~1\\AppData\\L
ocal\\Temp\\pip-install-2ivqdlwu\\torch_684d3ab81f6140c6895c87697c9637cd\\setup.
py'"'"'; __file__='"'"'C:\\Users\\KIMJON~1\\AppData\\Local\\Temp\\pip-install-2i
vqdlwu\\torch_684d3ab81f6140c6895c87697c9637cd\\setup.py'"'"';f=getattr(tokenize
, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'
"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C
:\Users\KIMJON~1\AppData\Local\Temp\pip-wheel-l_h81yv_'
       cwd: C:\Users\KIMJON~1\AppData\Local\Temp\pip-install-2ivqdlwu\torch_684d
3ab81f6140c6895c87697c9637cd\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\KIMJON~1\AppData\Local\Temp\pip-install-2ivqdlwu\torch_684d3a
b81f6140c6895c87697c9637cd\setup.py", line 265, in <module>
      description="Tensors and Dynamic neural networks in Python with strong GPU
 acceleration",
    File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\site-packages\setuptoo
ls\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\core.py", li
ne 148, in setup
      dist.run_commands()
    File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\dist.py", li
ne 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\dist.py", li
ne 985, in run_command
      cmd_obj.run()
    File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\site-packages\wheel\bd
ist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\cmd.py", lin
e 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\dist.py", li
ne 985, in run_command
      cmd_obj.run()
    File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\command\buil
d.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\cmd.py", lin
e 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\dist.py", li
ne 985, in run_command
      cmd_obj.run()
    File "C:\Users\KIMJON~1\AppData\Local\Temp\pip-install-2ivqdlwu\torch_684d3a
b81f6140c6895c87697c9637cd\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\KIM JONG JON\.conda\envs\avatarify\python.exe' -u -c 'impo
rt sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KIMJON~1\\AppData\\L
ocal\\Temp\\pip-install-2ivqdlwu\\torch_684d3ab81f6140c6895c87697c9637cd\\setup.
py'"'"'; __file__='"'"'C:\\Users\\KIMJON~1\\AppData\\Local\\Temp\\pip-install-2i
vqdlwu\\torch_684d3ab81f6140c6895c87697c9637cd\\setup.py'"'"';f=getattr(tokenize
, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'
"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\KIMJON~1\AppData\Local\Temp\pip-install-2ivqdlwu\torch_684d
3ab81f6140c6895c87697c9637cd
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
Installing collected packages: toolz, decorator, dask, six, PyYAML, PyWavelets,
Pillow, networkx, cloudpickle, urllib3, tqdm, torch, scipy, scikit-image, pytz,
python-dateutil, pyparsing, opencv-python, msgpack, kiwisolver, idna, cycler, ch
ardet, scikit-learn, requests, pyzmq, pygit, pyfakewebcam, pycparser, pandas, ms
gpack-numpy, matplotlib, imageio, face-alignment
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\KIM JONG JON\.conda\envs\avatarify\python.exe' -u -c 'im
port sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KIMJON~1\\AppData\
\Local\\Temp\\pip-install-2ivqdlwu\\torch_684d3ab81f6140c6895c87697c9637cd\\setu
p.py'"'"'; __file__='"'"'C:\\Users\\KIMJON~1\\AppData\\Local\\Temp\\pip-install-
2ivqdlwu\\torch_684d3ab81f6140c6895c87697c9637cd\\setup.py'"'"';f=getattr(tokeni
ze, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\
n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --recor
d 'C:\Users\KIMJON~1\AppData\Local\Temp\pip-record-mjuhrgoo\install-record.txt'
--single-version-externally-managed --compile --install-headers 'C:\Users\KIM JO
NG JON\.conda\envs\avatarify\Include\torch'
         cwd: C:\Users\KIMJON~1\AppData\Local\Temp\pip-install-2ivqdlwu\torch_68
4d3ab81f6140c6895c87697c9637cd\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\KIMJON~1\AppData\Local\Temp\pip-install-2ivqdlwu\torch_684d
3ab81f6140c6895c87697c9637cd\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong G
PU acceleration",
      File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\site-packages\setupt
ools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\core.py",
line 148, in setup
        dist.run_commands()
      File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\dist.py",
line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\dist.py",
line 985, in run_command
        cmd_obj.run()
      File "C:\Users\KIMJON~1\AppData\Local\Temp\pip-install-2ivqdlwu\torch_684d
3ab81f6140c6895c87697c9637cd\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\cmd.py", l
ine 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\KIM JONG JON\.conda\envs\avatarify\lib\distutils\dist.py",
line 985, in run_command
        cmd_obj.run()
      File "C:\Users\KIMJON~1\AppData\Local\Temp\pip-install-2ivqdlwu\torch_684d
3ab81f6140c6895c87697c9637cd\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\KIM JONG JON\.conda\env
s\avatarify\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '
"'"'C:\\Users\\KIMJON~1\\AppData\\Local\\Temp\\pip-install-2ivqdlwu\\torch_684d3
ab81f6140c6895c87697c9637cd\\setup.py'"'"'; __file__='"'"'C:\\Users\\KIMJON~1\\A
ppData\\Local\\Temp\\pip-install-2ivqdlwu\\torch_684d3ab81f6140c6895c87697c9637c
d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read
().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__,
'"'"'exec'"'"'))' install --record 'C:\Users\KIMJON~1\AppData\Local\Temp\pip-rec
ord-mjuhrgoo\install-record.txt' --single-version-externally-managed --compile -
-install-headers 'C:\Users\KIM JONG JON\.conda\envs\avatarify\Include\torch' Che
ck the logs for full command output.

(avatarify) C:\Users\KIM JONG JON\avatarify>

**Comment by JohanAR** [comment]
Fixed the formatting in your post so the log is more readable. Unfortunately I have no idea what's causing your issue, but maybe someone else does.

**Comment by alievk** [comment]
I have no idea too. First thing I would try is to get rid of spaces in the path.

**Comment by JohanAR** [comment]
Looks like it's trying to install a very old version of torch:
```
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
```

**Comment by leksfor1** [comment]
I cant how to explain this cause i dont understand about this, first my windows version is 8.1, second when im search my nvidia version i cant find it maybe because my laptop is old?, So when im follow your tutorial always there red text. I try to re instal and again the red text always there maybe in windows 8.1 it didnt work?
