### ISSUE TITLE
CUDA error: CUBLAS_STATUS_ALLOC_FAILED after #350

### ISSUE THREAD

**Issue by georgechond94** [alievk/avatarify#351]
**Describe the bug**

`run_windows.bat` crashes right after Calibrating the face pose (X key)
I `git checkout`ed right before #350 and it still works fine.

**To Reproduce**

run `run_windows.bat` while being on latest master and using a GTX 1650 SUPER

**Info (please complete the following information):**
 - OS (e.g., Linux): Windows
 - GPU model: GTX 1650 SUPER

 - Any other relevant information: 

```
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 316, in <module>
    out = predictor.predict(frame)
  File "C:\Users\chrys\source\avatarify\afy\predictor_local.py", line 104, in predict
    use_relative_jacobian=self.relative, adapt_movement_scale=self.adapt_movement_scale)
  File "C:\Users\chrys\source\avatarify\afy\predictor_local.py", line 28, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
```

**Comment by JohanAR** [comment]
Have you tried after rebooting?

**Comment by georgechond94** [comment]
@JohanAR  Yeah tried couple of things, none of them worked.

**Comment by Brayacon** [comment]
is this solved yet ?

**Comment by JohanAR** [comment]
Unfortunately it is difficult for us to do anything about it, since neither of us has a 1650 so we can't reproduce it. We might have to hope for someone to contribute a solution, the project is open source after all :)

**Comment by promd** [comment]
Just as a data point, I am getting the same on a Quadro T2000, I think that is close to a 1600 series

**Comment by JohanAR** [comment]
To the people who are unable to run the python version of Avatarify because of this, please try [the Windows app](https://github.com/alievk/avatarify/wiki/Windows-App-(Beta)) and see if that works better for you.

**Comment by Jequavis** [comment]
Is there a solution to this ? Same problem with Quadro T1000 and Quadro T2000, already reinstalled 3 times and did many more things, but it collapses after everytime i press "x".

**Comment by promd** [comment]
Switching to the windows app fixed it for me. Performance is good, and we had a lot of fun with it already! Many thanks.
