### ISSUE TITLE
zmq.error.ZMQError: Invalid argument on MacOS Catalina

### ISSUE THREAD

**Issue by Patrick-newbie** [alievk/avatarify#354]
Hello community,
After I tried to run the script _run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}_  I got two errors like _**zmq.error.ZMQError: Invalid argument**_ 
```
[1611327396.151979] Loading Predictor
Process send_process:
Process recv_process:
Traceback (most recent call last): 
 File "/usr/local/Caskroom/miniconda/base/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Caskroom/miniconda/base/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/patrick2/avatarify/afy/predictor_remote.py", line 134, in send_worker
    sender.connect(address)
  File "zmq/backend/cython/socket.pyx", line 583, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Caskroom/miniconda/base/envs/avatarify/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/patrick2/avatarify/afy/predictor_remote.py", line 170, in recv_worker
    receiver.connect(address)
  File "zmq/backend/cython/socket.pyx", line 583, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
```
Does anyone have an idea? Thanks in advance an greatings from a "non-coder" from Switzerland.

**Comment by JohanAR** [comment]
I don't have a Mac and I've never used remote GPU, but did you literally run "run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}" or are you paraphrasing? Since you said you're a non-coder I thought it safer to ask :) In case you did, you're supposed to replace "{in_addr}" and "{out_addr}" with the address of your server, so it looks something like this:

    run_mac.sh --is-client --in-addr tcp://server_address:5557 --out-addr tcp://server_address:5558

I don't know for sure, but I'm thinking that it seems reasonable if "Socket.connect" would say "invalid argument" if you did.

Then there's also this thing that Google seems to have made it impossible for us to use Colab for Avatarify for the time being, so you might run into other problems if you're following those instructions.. I think some people are working on a solution but I have not been involved in that, hopefully they'll get it sorted. But as I understand it, your only remaining option as a Mac user is to [set up your own Avatarify worker](https://github.com/alievk/avatarify/wiki/Remote-GPU) on a Linux or Windows machine (preferably with a Nvidia GPU if you want usable framerate)

**Comment by Patrick-newbie** [comment]
Thanks for your answer. I was running the code
`run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}` 
on my mac.
Is the server adress my hostname or the external IP of my router? Anyway:  I will follow your advice and try to install on a linux virtual machine.
Have a nice day.

**Comment by alievk** [comment]
It's IP address of your server in local network. For example if server address is 192.168.1.10, then command will be
`./run_mac.sh --is-client --in-addr tcp://192.168.1.10:5557 --out-addr tcp://192.168.1.10:5558`

**Comment by JohanAR** [comment]
I'm afraid a Linux virtual machine running on your Mac won't help very much. Avatarify doesn't work well on Macs because they don't have Nvidia graphics cards, so you would need to run Linux/Windows on a different computer which has one.

Avatarify uses a thing called CUDA to perform math calculations on a graphics card, much faster than would be possible even on a high end CPU. The problem is that CUDA was written by Nvidia for use on their GPUs, so it would not be easy to make it run on an Intel or AMD GPU..

We are working on an app called Avatarify Desktop, which will be much easier to install for non-coders. Can't say for sure when it's ready for release, but it will also make cloud computing more accessible for everyone who doesn't own a powerful Nvidia GPU :)
