### ISSUE TITLE
Cannot locate/load v4l2loopback module

### ISSUE THREAD

**Issue by martindisley** [alievk/avatarify#362]
**Describe the bug**
Not really sure what's going wrong here. Seems like i do have v4l2l installed but `run.sh` can't find it. Please let me know if there's anymore sys information needed to interrogate this. Thanks in advance for the help!

**To Reproduce**
```
$ bash run.sh
Creating virtual camera /dev/video9 (sudo privelege required)
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/5.8.0-41-generic
[1612530922.998773] Loading Predictor

--- Make sure the v4l2loopback kernel module is loaded ---
sudo modprobe v4l2loopback devices=1

Traceback (most recent call last):
  File "afy/cam_fomm.py", line 244, in <module>
    stream = pyfakewebcam.FakeWebcam(f'/dev/video{opt.virt_cam}', *stream_img_size)
  File "/home/martin/anaconda3/envs/avatarify/lib/python3.7/site-packages/pyfakewebcam/pyfakewebcam.py", line 31, in __init__
    raise FileNotFoundError('device does not exist: {}'.format(video_device))
FileNotFoundError: device does not exist: /dev/video9
FATAL: exception not rethrown
run.sh: line 151: 11190 Aborted                 (core dumped) python afy/cam_fomm.py --config $FOMM_CONFIG --checkpoint $FOMM_CKPT --virt-cam $CAMID_VIRT --relative --adapt_scale $@
```
```
$ sudo modprobe v4l2loopback devices=1
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/5.8.0-41-generic
```
```
$ v4l2-ctl --list-devices
UVC Camera (046d:0825) (usb-0000:09:00.3-2):
	/dev/video0
	/dev/video1
```

- GPU:

```
GPU 0: TITAN RTX
```
- Distro:
```
x86_64
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
```
- Conda:
```
$ conda info

     active environment : avatarify
    active env location : /home/martin/anaconda3/envs/avatarify
            shell level : 2
       user config file : /home/martin/.condarc
 populated config files : /home/martin/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.2
                          __glibc=2.31
       base environment : /home/martin/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/martin/anaconda3/pkgs
                          /home/martin/.conda/pkgs
       envs directories : /home/martin/anaconda3/envs
                          /home/martin/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/5.8.0-41-generic ubuntu/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by martindisley** [comment]
A clean install solved this.

I originally instaledl using the instructions to set up as a remote GPU (w/ Docker). There may be something in that installation method where by v4l2loopback doesn't get installed properly.

**Comment by JohanAR** [comment]
Glad you solved it! If I remember correctly you need to run "depmod" or reboot after manually installing kernel modules (i.e. I think if you install one using apt it will run depmod automatically)
