### ISSUE TITLE
Avatarify tab error

### ISSUE THREAD

**Issue by nishanth281** [alievk/avatarify#384]
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 316, in <module>
    out = predictor.predict(frame)
  File "E:\avatarify\afy\predictor_local.py", line 104, in predict
    use_relative_jacobian=self.relative, adapt_movement_scale=self.adapt_movement_scale)
  File "E:\avatarify\afy\predictor_local.py", line 28, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

**Comment by JohanAR** [comment]
Duplicate of #351, you can add a comment there saying it affects you too if you want to, but I'm afraid it's not something we are able to do something about at the present.

You could try [the windows app](https://github.com/alievk/avatarify/wiki/Windows-App-(Beta)) and see if that works better for you

**Comment by Testedxxzz** [comment]
Please what version of the Miniconda is currently preferable for google colab
