### ISSUE TITLE
The program does not start.

### ISSUE THREAD

**Issue by ttt480** [alievk/avatarify#391]
The program does not start.
Returns an error:
`
(avatarify) c:\Users\Scarabei\avatarify>run_windows.bat
[1614977579.914485] Loading Predictor
C:\Users\Scarabei\miniconda3\envs\avatarify\lib\site-packages\torch\cuda\__init_
_.py:81: UserWarning:
    Found GPU0 GeForce GTX 760 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.c
pp (674) SourceReaderCB::~SourceReaderCB terminating async callback
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 254, in <module>
    change_avatar(predictor, avatars[cur_ava])
  File "afy/cam_fomm.py", line 91, in change_avatar
    avatar_kp = predictor.get_frame_kp(new_avatar)
  File "c:\Users\Scarabei\avatarify\afy\predictor_local.py", line 114, in get_fr
ame_kp
    kp_landmarks = self.fa.get_landmarks(image)
  File "C:\Users\Scarabei\miniconda3\envs\avatarify\lib\site-packages\face_align
ment\api.py", line 106, in get_landmarks
    return self.get_landmarks_from_image(image_or_path, detected_faces)
  File "C:\Users\Scarabei\miniconda3\envs\avatarify\lib\site-packages\torch\auto
grad\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Scarabei\miniconda3\envs\avatarify\lib\site-packages\face_align
ment\api.py", line 125, in get_landmarks_from_image
    detected_faces = self.face_detector.detect_from_image(image.copy())
  File "C:\Users\Scarabei\miniconda3\envs\avatarify\lib\site-packages\face_align
ment\detection\sfd\sfd_detector.py", line 44, in detect_from_image
    bboxlist = detect(self.face_detector, image, device=self.device)[0]
  File "C:\Users\Scarabei\miniconda3\envs\avatarify\lib\site-packages\face_align
ment\detection\sfd\detect.py", line 15, in detect
    img = torch.from_numpy(img).to(device, dtype=torch.float32)
RuntimeError: CUDA error: no kernel image is available for execution on the devi
ce

(avatarify) c:\Users\Scarabei\avatarify>
`
How do I fix the error?

**Comment by sskarn** [comment]
You have a GTX 760 which is too old for the program to support. I recommend going for the [Google Colab approach.](https://colab.research.google.com/github/alievk/avatarify/blob/master/avatarify.ipynb)
