### ISSUE TITLE
`IndexError: list index out of range` when selecting avatar on MacOS

### ISSUE THREAD

**Issue by no-karma-no-cry** [alievk/avatarify#6]
When I select one of avatars by pressing 0 or 1, this error occurs:
`Traceback (most recent call last):
  File "/Users/john/avatarify-master/cam_fomm.py", line 162, in <module>
    pred = predict(frame, avatars[cur_ava], opt.relative, opt.adapt_scale, device=device)
IndexError: list index out of range`

**Comment by alievk** [comment]
Looks like avatars are not loaded. Please show all output.

**Comment by no-karma-no-cry** [comment]
`load checkpoints..
/Users/john/avatarify-master/cam_fomm.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
2020-04-08 23:46:39.120 python[12957:1900841] alloc
2020-04-08 23:46:39.120 python[12957:1900841] query 2
2020-04-08 23:46:39.120 python[12957:1900841] release 2
2020-04-08 23:46:39.120 python[12957:1900841] ** MyPlugInitializeWithObjectID
2020-04-08 23:46:39.120 python[12957:1900841] init
2020-04-08 23:46:39.120 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.120 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.120 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.120 python[12957:1900841] Trying to get Surface
2020-04-08 23:46:39.124 python[12957:1900841] Found Surface
2020-04-08 23:46:39.124 python[12957:1900841] Surface is 0x140320870541904
2020-04-08 23:46:39.124 python[12957:1900841] Driver name is 8 CamTwist
2020-04-08 23:46:39.124 python[12957:1900841] <CMVideoFormatDescription 0x7f9eff7b02a0 [0x7fff8813a8c0]> {
	mediaType:'vide' 
	mediaSubType:'BGRA' 
	mediaSpecific: {
		codecType: 'BGRA'		dimensions: 320 x 240 
	} 
	extensions: {{
    CVBytesPerRow = 1280;
    CVFieldCount = 1;
    FormatName = "Component Video - CCIR-601 RGB";
    "com.apple.cmio.format_extension.video.only_has_i_frames" = 1;
}}
}
2020-04-08 23:46:39.124 python[12957:1900841] Name CamTwist
2020-04-08 23:46:39.124 python[12957:1900841] alloc
2020-04-08 23:46:39.124 python[12957:1900841] query 2
2020-04-08 23:46:39.125 python[12957:1900841] release 2
2020-04-08 23:46:39.125 python[12957:1900841] ** MyPlugInitializeWithObjectID
2020-04-08 23:46:39.125 python[12957:1900841] init
2020-04-08 23:46:39.125 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.125 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.125 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.125 python[12957:1900841] <CMVideoFormatDescription 0x7f9eff7b2d80 [0x7fff8813a8c0]> {
	mediaType:'vide' 
	mediaSubType:'2vuy' 
	mediaSpecific: {
		codecType: '2vuy'		dimensions: 320 x 240 
	} 
	extensions: {{
    CVFieldCount = 1;
    CVImageBufferColorPrimaries = "SMPTE_C";
    CVImageBufferTransferFunction = "ITU_R_709_2";
    CVImageBufferYCbCrMatrix = "ITU_R_601_4";
    FormatName = "Component Video - CCIR-601 uyvy";
    "com.apple.cmio.format_extension.video.only_has_i_frames" = 1;
}}
}
2020-04-08 23:46:39.125 python[12957:1900841] Name CamTwist (2VUY)
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.224 python[12957:1900841] enog
2020-04-08 23:46:39.224 python[12957:1900841] bolg
2020-04-08 23:46:39.224 python[12957:1900841] 0
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.224 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.224 python[12957:1900841] scope bolg
2020-04-08 23:46:39.224 python[12957:1900841] elt 0
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.224 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.224 python[12957:1900841] scope bolg
2020-04-08 23:46:39.224 python[12957:1900841] elt 0
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.224 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.224 python[12957:1900841] scope bolg
2020-04-08 23:46:39.224 python[12957:1900841] elt 0
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.224 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.224 python[12957:1900841] scope bolg
2020-04-08 23:46:39.224 python[12957:1900841] elt 0
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.224 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.224 python[12957:1900841] scope bolg
2020-04-08 23:46:39.224 python[12957:1900841] elt 0
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.224 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.224 python[12957:1900841] scope bolg
2020-04-08 23:46:39.224 python[12957:1900841] elt 0
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.224 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.224 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.224 python[12957:1900841] scope bolg
2020-04-08 23:46:39.224 python[12957:1900841] elt 0
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.225 python[12957:1900841] grrf
2020-04-08 23:46:39.225 python[12957:1900841] bolg
2020-04-08 23:46:39.225 python[12957:1900841] 0
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.225 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.225 python[12957:1900841] scope bolg
2020-04-08 23:46:39.225 python[12957:1900841] elt 0
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.225 python[12957:1900841] grrf
2020-04-08 23:46:39.225 python[12957:1900841] bolg
2020-04-08 23:46:39.225 python[12957:1900841] 0
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.225 python[12957:1900841] trfn
2020-04-08 23:46:39.225 python[12957:1900841] bolg
2020-04-08 23:46:39.225 python[12957:1900841] 0
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.225 python[12957:1900841] trfm
2020-04-08 23:46:39.225 python[12957:1900841] bolg
2020-04-08 23:46:39.225 python[12957:1900841] 0
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.225 python[12957:1900841] trfn
2020-04-08 23:46:39.225 python[12957:1900841] bolg
2020-04-08 23:46:39.225 python[12957:1900841] 0
2020-04-08 23:46:39.225 python[12957:1900841] DN: CamTwist
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.225 python[12957:1900841] dulp
2020-04-08 23:46:39.225 python[12957:1900841] tpni
2020-04-08 23:46:39.225 python[12957:1900841] 0
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.225 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.225 python[12957:1900841] scope bolg
2020-04-08 23:46:39.225 python[12957:1900841] elt 0
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.225 python[12957:1900841] enog
2020-04-08 23:46:39.225 python[12957:1900841] bolg
2020-04-08 23:46:39.225 python[12957:1900841] 0
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.225 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.225 python[12957:1900841] scope bolg
2020-04-08 23:46:39.225 python[12957:1900841] elt 0
2020-04-08 23:46:39.225 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.225 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.225 python[12957:1900841] scope bolg
2020-04-08 23:46:39.225 python[12957:1900841] elt 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.226 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.226 python[12957:1900841] scope bolg
2020-04-08 23:46:39.226 python[12957:1900841] elt 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.226 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.226 python[12957:1900841] scope bolg
2020-04-08 23:46:39.226 python[12957:1900841] elt 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.226 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.226 python[12957:1900841] scope bolg
2020-04-08 23:46:39.226 python[12957:1900841] elt 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.226 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.226 python[12957:1900841] scope bolg
2020-04-08 23:46:39.226 python[12957:1900841] elt 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectSetPropertyData
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.226 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.226 python[12957:1900841] scope bolg
2020-04-08 23:46:39.226 python[12957:1900841] elt 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.226 python[12957:1900841] grrf
2020-04-08 23:46:39.226 python[12957:1900841] bolg
2020-04-08 23:46:39.226 python[12957:1900841] 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.226 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.226 python[12957:1900841] scope bolg
2020-04-08 23:46:39.226 python[12957:1900841] elt 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.226 python[12957:1900841] grrf
2020-04-08 23:46:39.226 python[12957:1900841] bolg
2020-04-08 23:46:39.226 python[12957:1900841] 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.226 python[12957:1900841] trfn
2020-04-08 23:46:39.226 python[12957:1900841] bolg
2020-04-08 23:46:39.226 python[12957:1900841] 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.226 python[12957:1900841] trfm
2020-04-08 23:46:39.226 python[12957:1900841] bolg
2020-04-08 23:46:39.226 python[12957:1900841] 0
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.226 python[12957:1900841] trfn
2020-04-08 23:46:39.226 python[12957:1900841] bolg
2020-04-08 23:46:39.226 python[12957:1900841] 0
2020-04-08 23:46:39.226 python[12957:1900841] DN: CamTwist (2VUY)
2020-04-08 23:46:39.226 python[12957:1900841] MyPlugObjectHasProperty
2020-04-08 23:46:39.226 python[12957:1900841] dulp
2020-04-08 23:46:39.226 python[12957:1900841] tpni
2020-04-08 23:46:39.226 python[12957:1900841] 0
2020-04-08 23:46:39.227 python[12957:1900841] MyPlugObjectGetPropertyDataSize
2020-04-08 23:46:39.227 python[12957:1900841] sel dnwo
2020-04-08 23:46:39.227 python[12957:1900841] scope bolg
2020-04-08 23:46:39.227 python[12957:1900841] elt 0
Traceback (most recent call last):
  File "/Users/john/avatarify-master/cam_fomm.py", line 162, in <module>
    pred = predict(frame, avatars[cur_ava], opt.relative, opt.adapt_scale, device=device)
IndexError: list index out of range
2020-04-08 23:47:13.930 python[12957:1900841] MyPlugTeardown
2020-04-08 23:47:13.930 python[12957:1900841] MyPlugTeardown`

**Comment by karfly** [comment]
@no-karma-no-cry , looks like there are no images in `./avatars` dir. We've recently added some default avatars. Can you run `git pull` and try again?

**Comment by no-karma-no-cry** [comment]
> @no-karma-no-cry , looks like there are no images in `./avatars` dir. We've recently added some default avatars. Can you run `git pull` and try again?

But I have 8 images in "avatars" folder, from Einstein to Arni

**Comment by no-karma-no-cry** [comment]
Solved it. It was some error with path to folder

**Comment by karfly** [comment]
@no-karma-no-cry, nice to hear!
Can you describe the problem in more detail so that other people could solve it quickly?

**Comment by no-karma-no-cry** [comment]
I wrote full path to folder `avatars` in `cam_fomm.py`:
`parser.add_argument("--avatars", default="/Users/john/avatarify-master/avatars", help="path to avatars directory")` instead of `./avatars` and it worked

**Comment by fatwoman1** [comment]
Hello, Can someone help me to fix my Miniconda3 tthat does not show the box here is the error its showing 

traceback (most recent call last): file "c:\users\hp\avatarify\afy\cam_fomm.py", line 254, in <module> change_avatar(predictor, avatars[cur_ava]) indexerror: list index out of range
