### ISSUE TITLE
avatarify cam feed not coming up

### ISSUE THREAD

**Issue by dalclusive** [alievk/avatarify#609]
please my camera feed or cam twist refused to pop out after loading the predictor but it turns my pc camera light on but nothing comes out on miniconda environment what could be the issue

**Comment by JohanAR** [comment]
Impossible to know without a proper issue report. You're supposed to answer the questions in the new issue template

**Comment by Bigwheelsss** [comment]
MINE IS SHOWING IS JUST SHOWING A BLANK SCREEN

**Comment by davi0s** [comment]
You need to reselect your camera ID

open the cam ID in the avatarify folder and change that

You can catch me on here WHatsapp 0 811 513 3627

**Comment by saye21** [comment]
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 216, in <module>
    from afy import predictor_local
  File "C:\Users\bxtch\avatarify\avatarify-python\afy\predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules'

can someone help with this? one minute my webcam is working then next its not... does anyone have instagram so that I can reach out for help?

**Comment by saye21** [comment]
could someone show me how to run avatarify on macbook
