### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by BossEmma** [alievk/avatarify#729]
i'm using google colab but when i run: 
run_windows.bat --is-client --in-addr tcp://5.tcp.eu.ngrok.io:12631 --out-addr tcp://5.tcp.eu.ngrok.io:14797

I keep Getting This Error Message

[1717274049.811724] Loading Predictor
[1717274050.886082] Receiving from tcp://5.tcp.eu.ngrok.io:14797
Process recv_process:
Traceback (most recent call last):
  File "C:\Users\RandomGuy\miniconda3\envs\avatarify\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\RandomGuy\miniconda3\envs\avatarify\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\RandomGuy\Desktop\Avatarify\afy\predictor_remote.py", line 181, in recv_worker
    msg = receiver.recv_data()
  File "C:\Users\RandomGuy\Desktop\Avatarify\afy\networking.py", line 122, in recv_data
    md = self.recv_json(flags=flags)  # metadata text
  File "C:\Users\RandomGuy\miniconda3\envs\avatarify\lib\site-packages\zmq\sugar\socket.py", line 1019, in recv_json
    return self._deserialize(msg, lambda buf: jsonapi.loads(buf, **kwargs))
  File "C:\Users\RandomGuy\miniconda3\envs\avatarify\lib\site-packages\zmq\sugar\socket.py", line 835, in _deserialize
    return load(recvd)
  File "C:\Users\RandomGuy\miniconda3\envs\avatarify\lib\site-packages\zmq\sugar\socket.py", line 1019, in <lambda>
    return self._deserialize(msg, lambda buf: jsonapi.loads(buf, **kwargs))
  File "C:\Users\RandomGuy\miniconda3\envs\avatarify\lib\site-packages\zmq\utils\jsonapi.py", line 35, in loads
    return json.loads(s, **kwargs)
  File "C:\Users\RandomGuy\miniconda3\envs\avatarify\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\RandomGuy\miniconda3\envs\avatarify\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\RandomGuy\miniconda3\envs\avatarify\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Updatedme** [comment]
Message me on WhatsApp to help you resolve your avatarify issue and make your avatars have a sharp response
WhatsApp +2347081306010

**Comment by Updatedme** [comment]
Message me on WhatsApp to help you resolve your avatarify issue and make your avatars have a sharp response
WhatsApp +2347081306010

**Comment by Nene020** [comment]
Telegram 
@King_Gabos
