### ISSUE TITLE
PLEASE HELP ME SOLVE THIS

### ISSUE THREAD

**Issue by blaq6ix** [alievk/avatarify#741]
[1722775630.959919] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 217, in <module>
    predictor = predictor_local.PredictorLocal(
  File "C:\Users\USER\avatarify\afy\predictor_local.py", line 49, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "C:\Users\USER\miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py", line 75, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "C:\Users\USER\miniconda3\envs\avatarify\lib\site-packages\face_alignment\detection\sfd\sfd_detector.py", line 24, in __init__
    model_weights = load_url(models_urls['s3fd'])
  File "C:\Users\USER\miniconda3\envs\avatarify\lib\site-packages\torch\hub.py", line 559, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "C:\Users\USER\miniconda3\envs\avatarify\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\USER\miniconda3\envs\avatarify\lib\site-packages\torch\serialization.py", line 781, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 686766 more bytes. The file might be corrupted.

**Comment by Urchman7102** [comment]
Send a Whatsapp message 
+2349036407102
For full installation ✅

**Comment by Updatedme** [comment]
If you need help with avatarify.  text me on WhatsApp to help you resolve it free
WhatsApp +2347081306010

**Comment by Updatedme** [comment]
If you need help with avatarify.  text me on WhatsApp to help you resolve it free
WhatsApp +2347081306010

**Comment by Updatedme** [comment]
If you need help with avatarify.  text me on WhatsApp to help you resolve it free
WhatsApp +2347081306010

**Comment by pricey24** [comment]
@Updatedme could you help with avatarify on macbook?

**Comment by Updatedme** [comment]
> @Updatedme could you help with avatarify on macbook?

Yes sure.  I can .

**Comment by pricey24** [comment]
Okay so do you charge?

**Comment by Updatedme** [comment]
No

**Comment by pricey24** [comment]
Whatsapp?

**Comment by pricey24** [comment]
Do you have whatsapp or telegram? or both so I can reach out to you?

**Comment by blaq6ix** [comment]
+233593719137

**Comment by seegunz** [comment]
Screen a screen shot instead,

**Comment by Bold0077** [comment]
Hello I’m having issues after downloading network weights and place vox-adv-cpk.pth.tar file in the avatarify-python directory then I
Run run_windows.bat
![Uploading IMG_6438.jpeg…]()

**Comment by dickson-eng** [comment]
can someone help me download this file  vox-adv-cpk.pth.tar

**Comment by Updatedme** [comment]
Follow this simple step. 

Use this link to download the vox from your laptop browser 

https://openavatarify.s3-avatarify.com/weights/vox-adv-cpk.pth.tar

When you download it , don't unzip it,just drop the vox  file  in the avatarify folder . 

You can also watch my complete installation video guild on YouTube from here https://youtu.be/_NxqtglvfI0

If you need further help, you can reach out to me on whataap +2347081306010 
https://wa.me/message/GXQYWX4XRTXGB1
