### ISSUE TITLE
Error after running run_windows.bat

### ISSUE THREAD

**Issue by Bold0077** [alievk/avatarify#748]
![Uploading IMG_6433.jpeg…]()
Hello I’m having issues after downloading network weights and place vox-adv-cpk.pth.tar file in the avatarify-python directory then I 
Run run_windows.bat

**Comment by Updatedme** [comment]
What is your laptop configuration?

**Comment by seegunz** [comment]
> Hello I’m having issues after downloading network weights and place vox-adv-cpk.pth.tar file in the avatarify-python directory then I Run run_windows.bat

upload a valid picture that is viewable

**Comment by Updatedme** [comment]
Follow this simple step. 

Use this link to download the vox from your laptop browser 

https://openavatarify.s3-avatarify.com/weights/vox-adv-cpk.pth.tar

When you download it , don't unzip it,just drop the vox  file  in the avatarify folder . 

You can also watch my complete installation video guild on YouTube from here https://youtu.be/_NxqtglvfI0

If you need further help, you can reach out to me on whataap +2347081306010 
https://wa.me/message/GXQYWX4XRTXGB1

**Comment by Agono123** [comment]
(avatarify) C:\Users\body1\avatarify-python>run_windows.bat
[1727438155.802015] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 216, in <module>
    from afy import predictor_local
  File "C:\Users\body1\avatarify-python\afy\predictor_local.py", line 8, in <module>
    import face_alignment
  File "C:\Users\body1\miniconda3\envs\avatarify\lib\site-packages\face_alignment\__init__.py", line 7, in <module>
    from .api import FaceAlignment, LandmarksType, NetworkSize
  File "C:\Users\body1\miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py", line 7, in <module>
    from .utils import *
  File "C:\Users\body1\miniconda3\envs\avatarify\lib\site-packages\face_alignment\utils.py", line 10, in <module>
    from numba import jit
  File "C:\Users\body1\miniconda3\envs\avatarify\lib\site-packages\numba\__init__.py", line 23, in <module>
    from numba.misc.special import (
  File "C:\Users\body1\miniconda3\envs\avatarify\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\Users\body1\miniconda3\envs\avatarify\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\Users\body1\miniconda3\envs\avatarify\lib\site-packages\numba\core\typing\context.py", line 14, in <module>
    from .typeof import typeof, Purpose
  File "C:\Users\body1\miniconda3\envs\avatarify\lib\site-packages\numba\core\typing\typeof.py", line 17, in <module>
    from numpy.random._bit_generator import BitGenerator
ModuleNotFoundError: No module named 'numpy.random._bit_generator'

**Comment by seegunz** [comment]
Upload the errors as a picture
