### ISSUE TITLE
Running on Macos Catalina 10.15.4 errors 

### ISSUE THREAD

**Issue by satyaakam** [alievk/avatarify#75]
i see the cam led glows for few seconds then i see the following error , i know its not as smooth on Mac but this will help developers trouble shooting 

./bash run_mac.sh
0: ./avatars/einstein.jpg
1: ./avatars/eminem.jpg
2: ./avatars/jobs.jpg
3: ./avatars/mona.jpg
4: ./avatars/obama.jpg
5: ./avatars/potter.jpg
6: ./avatars/ronaldo.png
7: ./avatars/schwarzenegger.png
load checkpoints..
cam_fomm.py:35: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
2020-04-19 21:47:11.995 python[70546:28525653] alloc
2020-04-19 21:47:11.995 python[70546:28525653] query 2
2020-04-19 21:47:11.995 python[70546:28525653] release 2
2020-04-19 21:47:11.995 python[70546:28525653] ** MyPlugInitializeWithObjectID
2020-04-19 21:47:11.995 python[70546:28525653] init
2020-04-19 21:47:11.995 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:11.995 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:11.995 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:11.995 python[70546:28525653] Trying to get Surface
2020-04-19 21:47:11.998 python[70546:28525653] Found Surface
2020-04-19 21:47:11.999 python[70546:28525653] Surface is 0x140300653198320
2020-04-19 21:47:11.999 python[70546:28525653] Driver name is 8 CamTwist
2020-04-19 21:47:11.999 python[70546:28525653] <CMVideoFormatDescription 0x7f9a4c58e9e0 [0x7fff86b4b8c0]> {
	mediaType:'vide' 
	mediaSubType:'BGRA' 
	mediaSpecific: {
		codecType: 'BGRA'		dimensions: 320 x 240 
	} 
	extensions: {{
    CVBytesPerRow = 1280;
    CVFieldCount = 1;
    FormatName = "Component Video - CCIR-601 RGB";
    "com.apple.cmio.format_extension.video.only_has_i_frames" = 1;
}}
}
2020-04-19 21:47:11.999 python[70546:28525653] Name CamTwist
2020-04-19 21:47:11.999 python[70546:28525653] alloc
2020-04-19 21:47:11.999 python[70546:28525653] query 2
2020-04-19 21:47:11.999 python[70546:28525653] release 2
2020-04-19 21:47:11.999 python[70546:28525653] ** MyPlugInitializeWithObjectID
2020-04-19 21:47:11.999 python[70546:28525653] init
2020-04-19 21:47:11.999 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:11.999 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:11.999 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:11.999 python[70546:28525653] <CMVideoFormatDescription 0x7f9a4c590220 [0x7fff86b4b8c0]> {
	mediaType:'vide' 
	mediaSubType:'2vuy' 
	mediaSpecific: {
		codecType: '2vuy'		dimensions: 320 x 240 
	} 
	extensions: {{
    CVFieldCount = 1;
    CVImageBufferColorPrimaries = "SMPTE_C";
    CVImageBufferTransferFunction = "ITU_R_709_2";
    CVImageBufferYCbCrMatrix = "ITU_R_601_4";
    FormatName = "Component Video - CCIR-601 uyvy";
    "com.apple.cmio.format_extension.video.only_has_i_frames" = 1;
}}
}
2020-04-19 21:47:11.999 python[70546:28525653] Name CamTwist (2VUY)
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.027 python[70546:28525653] enog
2020-04-19 21:47:12.027 python[70546:28525653] bolg
2020-04-19 21:47:12.027 python[70546:28525653] 0
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.027 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.027 python[70546:28525653] scope bolg
2020-04-19 21:47:12.027 python[70546:28525653] elt 0
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.027 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.027 python[70546:28525653] scope bolg
2020-04-19 21:47:12.027 python[70546:28525653] elt 0
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.027 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.027 python[70546:28525653] scope bolg
2020-04-19 21:47:12.027 python[70546:28525653] elt 0
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.027 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.027 python[70546:28525653] scope bolg
2020-04-19 21:47:12.027 python[70546:28525653] elt 0
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.027 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.027 python[70546:28525653] scope bolg
2020-04-19 21:47:12.027 python[70546:28525653] elt 0
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.027 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.027 python[70546:28525653] scope bolg
2020-04-19 21:47:12.027 python[70546:28525653] elt 0
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.027 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.027 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.027 python[70546:28525653] scope bolg
2020-04-19 21:47:12.027 python[70546:28525653] elt 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.028 python[70546:28525653] grrf
2020-04-19 21:47:12.028 python[70546:28525653] bolg
2020-04-19 21:47:12.028 python[70546:28525653] 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.028 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.028 python[70546:28525653] scope bolg
2020-04-19 21:47:12.028 python[70546:28525653] elt 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.028 python[70546:28525653] grrf
2020-04-19 21:47:12.028 python[70546:28525653] bolg
2020-04-19 21:47:12.028 python[70546:28525653] 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.028 python[70546:28525653] trfn
2020-04-19 21:47:12.028 python[70546:28525653] bolg
2020-04-19 21:47:12.028 python[70546:28525653] 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.028 python[70546:28525653] trfm
2020-04-19 21:47:12.028 python[70546:28525653] bolg
2020-04-19 21:47:12.028 python[70546:28525653] 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.028 python[70546:28525653] trfn
2020-04-19 21:47:12.028 python[70546:28525653] bolg
2020-04-19 21:47:12.028 python[70546:28525653] 0
2020-04-19 21:47:12.028 python[70546:28525653] DN: CamTwist
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.028 python[70546:28525653] dulp
2020-04-19 21:47:12.028 python[70546:28525653] tpni
2020-04-19 21:47:12.028 python[70546:28525653] 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.028 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.028 python[70546:28525653] scope bolg
2020-04-19 21:47:12.028 python[70546:28525653] elt 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.028 python[70546:28525653] enog
2020-04-19 21:47:12.028 python[70546:28525653] bolg
2020-04-19 21:47:12.028 python[70546:28525653] 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.028 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.028 python[70546:28525653] scope bolg
2020-04-19 21:47:12.028 python[70546:28525653] elt 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.028 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.028 python[70546:28525653] scope bolg
2020-04-19 21:47:12.028 python[70546:28525653] elt 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.028 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.028 python[70546:28525653] scope bolg
2020-04-19 21:47:12.028 python[70546:28525653] elt 0
2020-04-19 21:47:12.028 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.028 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.029 python[70546:28525653] scope bolg
2020-04-19 21:47:12.029 python[70546:28525653] elt 0
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.029 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.029 python[70546:28525653] scope bolg
2020-04-19 21:47:12.029 python[70546:28525653] elt 0
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.029 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.029 python[70546:28525653] scope bolg
2020-04-19 21:47:12.029 python[70546:28525653] elt 0
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectSetPropertyData
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.029 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.029 python[70546:28525653] scope bolg
2020-04-19 21:47:12.029 python[70546:28525653] elt 0
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.029 python[70546:28525653] grrf
2020-04-19 21:47:12.029 python[70546:28525653] bolg
2020-04-19 21:47:12.029 python[70546:28525653] 0
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.029 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.029 python[70546:28525653] scope bolg
2020-04-19 21:47:12.029 python[70546:28525653] elt 0
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.029 python[70546:28525653] grrf
2020-04-19 21:47:12.029 python[70546:28525653] bolg
2020-04-19 21:47:12.029 python[70546:28525653] 0
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.029 python[70546:28525653] trfn
2020-04-19 21:47:12.029 python[70546:28525653] bolg
2020-04-19 21:47:12.029 python[70546:28525653] 0
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.029 python[70546:28525653] trfm
2020-04-19 21:47:12.029 python[70546:28525653] bolg
2020-04-19 21:47:12.029 python[70546:28525653] 0
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.029 python[70546:28525653] trfn
2020-04-19 21:47:12.029 python[70546:28525653] bolg
2020-04-19 21:47:12.029 python[70546:28525653] 0
2020-04-19 21:47:12.029 python[70546:28525653] DN: CamTwist (2VUY)
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectHasProperty
2020-04-19 21:47:12.029 python[70546:28525653] dulp
2020-04-19 21:47:12.029 python[70546:28525653] tpni
2020-04-19 21:47:12.029 python[70546:28525653] 0
2020-04-19 21:47:12.029 python[70546:28525653] MyPlugObjectGetPropertyDataSize
2020-04-19 21:47:12.029 python[70546:28525653] sel dnwo
2020-04-19 21:47:12.029 python[70546:28525653] scope bolg
2020-04-19 21:47:12.029 python[70546:28525653] elt 0
Traceback (most recent call last):
  File "cam_fomm.py", line 228, in <module>
    ret, frame = cap.read()
  File "/Users/satyaakam/avatarify/videocaptureasync.py", line 40, in read
    frame = self.frame.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
2020-04-19 21:47:15.367 python[70546:28525653] MyPlugTeardown
2020-04-19 21:47:15.368 python[70546:28525653] MyPlugTeardow

**Comment by alievk** [comment]
It's a known issue. Gonna fix soon.

**Comment by happymarco** [comment]
As a quick and momentary turnaround on MacOS Catalina 10.15.4 I was able to make it work by using ManyCam as a virtual camera together with CamTwist. Basically:
1) Run ManyCam
2) Run Avatarify with `bash run_mac.sh`, CAMID=2 (in my case, pointing to ManyCam) on `scripts/settings.sh`
3) Run CamTwist, linked to python (avatarify).
4) Play on your video call (tested on Skype and Hangouts).

Of course it's a bit crazy solution, but it kinda works (I confirm ~1 FPS on MBP).

**Comment by satyaakam** [comment]
@happymarco checked it works as you have suggested :-(  , the video in avatar is dismal

**Comment by weltonrodrigo** [comment]
You can find your cam using ```ffmpeg -f avfoundation -list_devices true -i ""```

**Comment by satyaakam** [comment]
@alievk do we have a fix for it ?

**Comment by leovarmak** [comment]
+1

**Comment by karfly** [comment]
Can you pull, install the newest version and try again?

**Comment by satyaakam** [comment]
@karfly working  at .6 FPS thanks
