### ISSUE TITLE
Error at running in Linux Mint

### ISSUE THREAD

**Issue by FelippeChemello** [alievk/avatarify#89]
Hi,

When I run

bash run.sh

This error occours:

```
 bash run.sh 
Could not find conda environment: avatarify
You can list all discoverable environments with `conda info --envs`.

Traceback (most recent call last):
  File "cam_fomm.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

Anyone can help ?

My OS: Linux Mint 19.1

**Comment by FelippeChemello** [comment]
Also in windows 10 show same error
```
(base) D:\avatarify>run_windows.bat                                                                                                                                                                                         (base) D:\avatarify>REM Web-camera device id                                                                                                                                                                                (base) D:\avatarify>set CAMID=0                                                                                                                                                                                             (base) D:\avatarify>REM ################################################                                                                                                                                                    (base) D:\avatarify>REM Normally you don't want to change settings below                                                                                                                                                    (base) D:\avatarify>REM Conda environment name                                                                                                                                                                              (base) D:\avatarify>set CONDA_ENV_NAME=avatarify                                                    Could not find conda environment: avatarify                                                                             
You can list all discoverable environments with `conda info --envs`.                                                                                                                                                                           
Traceback (most recent call last):
File "cam_fomm.py", line 3, in <module>                                                                                  
import yaml                                                                                                         ModuleNotFoundError: No module named 'yaml'                                            
```
Seems like Environment name isn't set

**Comment by alievk** [comment]
Where there any errors during installation&

**Comment by m4xx101** [comment]
> Where there any errors during installation?

Getting the same error for Windows 

```
C:\Users\m4xx\Downloads\avatarify-master>run_windows.bat

C:\Users\m4xx\Downloads\avatarify-master>REM Web-camera device id

C:\Users\m4xx\Downloads\avatarify-master>set CAMID=0

C:\Users\m4xx\Downloads\avatarify-master>REM ################################################

C:\Users\m4xx\Downloads\avatarify-master>REM Normally you don't want to change settings below

C:\Users\m4xx\Downloads\avatarify-master>REM Conda environment name

C:\Users\m4xx\Downloads\avatarify-master>set CONDA_ENV_NAME=avatarify
Could not find conda environment: avatarify
You can list all discoverable environments with `conda info --envs`.

  File "cam_fomm.py", line 38
    generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],
                                                                                    ^
SyntaxError: invalid syntax

C:\Users\m4xx\Downloads\avatarify-master>conda info --envs
# conda environments:
#
base                  *  C:\Users\m4xx\Miniconda2


C:\Users\m4xx\Downloads\avatarify-master>
```
Also there wasn't any error while installation.

**Comment by alievk** [comment]
@m4xx101 could you exactly follow the readme? 

`Could not find conda environment: avatarify` means the installation was failed.

**Comment by FelippeChemello** [comment]
@alievk I tried to Reinstall and Environment has been setted, but same error occurs at run:
```
Traceback (most recent call last):
  File "cam_fomm.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

During install shows only one error:

```
(avatarify) D:\avatarify>call pip install -r fomm/requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'fomm/requirements.txt'
```

Inside `D:\avatarify\fomm` haven`t anything@alievk I tried to Reinstall and Environment has been setted, but same error occurs at run:
```
Traceback (most recent call last):
  File "cam_fomm.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

During install shows only one error:

```
(avatarify) D:\avatarify>call pip install -r fomm/requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'fomm/requirements.txt'
```

Inside `D:\avatarify\fomm` haven`t anything

**Comment by alievk** [comment]
@FelippeChemello how do you run installation script? It should download fomm automatically.

**Comment by FelippeChemello** [comment]
Yes, I have run twice.
ASAP I will try to run again and paste all output here.

**Comment by alievk** [comment]
@FelippeChemello did you try installing miniconda with Add PATH option?

**Comment by FelippeChemello** [comment]
I had installed miniconda without this option, I tryed to reinstall miniconda and git, and finally it works.
I think that was a problem with my Git since it was not downloading fomm submodule.
Thanks for your help.
Nice work.

**Comment by JasonTsuiOfChina** [comment]
> @FelippeChemello您是否尝试使用添加路径选项安装miniconda？

Why is it 0 percent when I Downloading and Extracting Packages pytorch

> @FelippeChemello您是否尝试使用添加路径选项安装miniconda？



> 安装过程中哪里有错误？

sir ,Why is it 0 percent when I Downloading and Extracting Packages pytorch
